'use strict';
const KEY='haoxuan-training-log:v1';
const B=[['高位下拉','ラットプルダウン','Lat Pulldown',47.5,3,'8–12'],['坐姿划船','シーテッドロー','Seated Row',47.5,3,'8–12'],['反向飞鸟','リアデルトフライ','Rear Delt Fly',19,2,'12–15'],['绳索面拉','フェイスプル','Face Pull',21.25,2,'12–15'],['二头弯举','アームカール','Arm Curl','',2,'8–12']].map(([cn,ja,en,weight,count,range])=>({cn,ja,en,weight,count,range}));
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
let db={version:1,templates:{A:[],B,C:[],D:[]},records:{},sleep:{},gym:'Anytime成增'},blocked=false;
try{const raw=localStorage.getItem(KEY);if(raw){const x=JSON.parse(raw);if(!isObject(x)||(x.version!==undefined&&x.version!==1))throw Error();db=x;blocked=!readableRoot(x)}}catch{blocked=true}
let date=today(),statusDate=today(),type='B',view='training';
const workoutDrafts={};
const existing=getAllNormalizedWorkouts(db).filter(r=>r.date===date).sort((a,b)=>(b.updated||0)-(a.updated||0));if(existing[0])type=existing[0].type;
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function record(){const id=`${date}_${type}`,found=editableWorkout(date,type);if(found)return found;if(!workoutDrafts[id]){const unsafe=blocked||scanWorkouts(db).unknown.length;workoutDrafts[id]=!unsafe&&type==='D'?newCardioRecord(date,db.gym):{date,type,gym:db.gym||'',exercises:unsafe?[]:templateFor(type).map(e=>({...e,done:false,sets:Array.from({length:e.count},()=>({weight:e.weight,reps:'',feel:'',rir:'',done:false}))})),feedback:{},completed:false,unrecognized:!!unsafe}}return workoutDrafts[id]}
function recordsForWrite(data){if(Array.isArray(data.records)){data.recoveryLegacyRecords=cloneData(data.records);return {}}return isObject(data.records)?{...data.records}:{}}
function save(){if(blocked||(view==='training'&&record().unrecognized)){$('#save-status').textContent='保存不可用 · 请备份';return false}try{if(view==='training'){const r=record();db.records={...recordsForWrite(db),[`${date}_${type}`]:r}}localStorage.setItem(KEY,JSON.stringify(db));$('#save-status').textContent='● 已自动保存';return true}catch{$('#save-status').textContent='保存失败 · 空间不足';toast('无法保存，请保留页面并复制训练反馈备份');return false}}
function toast(t){$('#toast').textContent=t;$('#toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.display='none',3000)}
function choices(path,values,current,cols=values.length){return `<div class="choices" style="--cols:${cols}">${values.map(v=>{const [value,label]=Array.isArray(v)?v:[v,v];return `<button type="button" data-choice="${path}" data-value="${esc(value)}" aria-pressed="${String(current)===String(value)}">${label}</button>`}).join('')}</div>`}
function field(label,path,value,kind='text',extra=''){return `<label class="form-field">${label}<span class="input-wrap"><input type="${kind}" ${kind==='time'&&!value?'class="time-empty"':''} data-field="${path}" value="${esc(value)}" ${extra}></span></label>`}
const feelings=[['easy','🟢 轻松'],['normal','🟡 普通'],['hard','🟠 困难'],['max','🔴 极限']],emoji={easy:'🟢',normal:'🟡',hard:'🟠',max:'🔴'};
function stepper(label,path,value,step){return `<div><label>${label}</label><div class="stepper"><button data-step="${path}" data-delta="-${step}" aria-label="减少${label}">−</button><input aria-label="${label}" data-field="${path}" type="number" inputmode="${step===1?'numeric':'decimal'}" min="0" max="${step===1?999:2000}" step="${step===1?1:0.01}" value="${esc(value)}"><button data-step="${path}" data-delta="${step}" aria-label="增加${label}">+</button></div></div>`}
function updateProgress(){if(view!=='training')return;if(record().kind==='cardio')return cardioProgress();const r=record(),all=r.exercises.flatMap(e=>e.sets),n=all.filter(s=>s.done).length;$('#progress-text').textContent=`${n} / ${all.length} 组 · ${r.exercises.filter(e=>e.done).length} / ${r.exercises.length} 动作`;$('#progress').value=n;$('#progress').max=all.length||1;$('#finish').disabled=!r.exercises.length||!r.exercises.every(e=>e.done);$('#finish').textContent=r.completed?'✓ 训练已完成':'结束训练并保存'}
function render(){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view||(view==='diagnostics'&&b.dataset.view==='history')));if(view==='training'){renderTraining();refreshPain();const entry=document.createElement('section');entry.className='import-entry';entry.innerHTML='<button id="open-import" class="primary full">导入今日计划</button>';const empty=$('#app .empty');(empty||$('#app .session')).after(entry);const notice=recoveryNotice();if(notice){const el=document.createElement('p');el.className='panel recovery-notice';el.textContent=notice;$('#app .session').after(el)}}if(view==='sleep')renderDailyStatus();if(view==='history')renderHistory();if(view==='diagnostics')renderDiagnostics();if(blocked)$('#save-status').textContent='保存不可用 · 请备份'}
function renderTraining(){const r=record();if(r.kind==='cardio')return renderCardio();$('#app').innerHTML=`<div class="row"><div><div class="eyebrow">YOUR DAILY SESSION</div><h1>${date===today()?'今日训练':'训练记录'}</h1></div><span class="badge">${type} DAY</span></div><section class="panel session"><div class="grid2">${field('训练日期','date',date,'date')}${field('健身房','gym',r.gym)}</div><label>训练类型</label>${choices('type',['A','B','C','D'],type)}<div class="row progress-label"><span>完成进度</span><span id="progress-text"></span></div><progress id="progress" aria-label="训练完成进度"></progress></section>${planContext(r)}<div class="row section-title"><h2>训练动作</h2><span class="counter">${r.exercises.length} 个动作</span></div>${r.exercises.map((e,i)=>`<details class="exercise" ${!e.done&&i===(r.exercises.findIndex(x=>!x.done))?'open':''}><summary><span class="exercise-number">${e.done?'✓':String(i+1).padStart(2,'0')}</span><div class="names"><h3>${esc(e.cn)}</h3><small lang="ja">${esc(e.ja)}</small><small lang="en">${esc(e.en)}</small></div><span class="counter">⌄</span></summary><div class="target">建议 ${e.weight===''?'重量待填':esc(e.weight)+' kg'} <span style="float:right">${e.count} 组 × ${esc(e.range)} 次</span></div>${importedExerciseInfo(e)}${e.sets.map((s,j)=>`<div class="set ${s.done?'done':''}"><div class="row"><span class="set-title">SET ${String(j+1).padStart(2,'0')}</span><span class="counter">${s.done?'已完成':'记录本组'}</span></div><div class="grid2">${stepper('重量 kg',`exercises.${i}.sets.${j}.weight`,s.weight,2.5)}${stepper('次数',`exercises.${i}.sets.${j}.reps`,s.reps,1)}</div><label>本组体感</label>${choices(`exercises.${i}.sets.${j}.feel`,feelings,s.feel)}<label>RIR · 还能做几次</label>${choices(`exercises.${i}.sets.${j}.rir`,['0','1','2','3','4+'],s.rir)}<button class="complete-set full" data-set="${i}.${j}" aria-pressed="${s.done}">${s.done?'✓ 已完成 · 点击撤销':'完成本组'}</button></div>`).join('')}<button class="primary full" data-exercise="${i}" ${!e.sets.every(s=>s.done)?'disabled':''}>${e.done?'✓ 动作已完成 · 点击撤销':'标记动作完成'}</button></details>`).join('')}${!r.exercises.length?'<div class="panel empty"><div class="empty-state-content"><h3>今天还没有训练计划</h3><p class="muted">从 ChatGPT 获取今日训练计划后即可导入。</p></div></div>':''}${type!=='B'&&!r.unrecognized?templateForm():''}<div class="section-title"><h2>训练结束反馈</h2></div><section class="panel">${feedback(r)}<button id="finish" class="primary full"></button><button id="generate" class="full">生成训练反馈 ↗</button></section><p class="muted">数据保存在此设备的浏览器中。首次在线打开后可离线使用。</p>`;updateProgress()}
function feedback(r){return [['总体体感','overall',['很好','正常','疲劳','很差']],['肌肉刺激','stimulus',['弱','正好','强']],['关节疼痛','pain',['无','有']]].map(([l,k,v])=>`<label>${l}</label>${choices('feedback.'+k,v,r.feedback[k])}`).join('')+`<div id="pain-area" ${r.feedback.pain!=='有'?'hidden':''}><label>疼痛部位（可多选）</label>${choices('painAreas',['肩','肘','腕','腰','膝','其他'],'',3).replace(/aria-pressed="false"/g,'aria-pressed="false"')}</div><label>备注（可选）<textarea data-field="feedback.notes">${esc(r.feedback.notes)}</textarea></label>`}
function templateForm(){return `<details class="panel"><summary>＋ 添加预设动作</summary><form id="add-exercise">${field('中文名','draft.cn',draft.cn||'','text','required')}${field('日文名','draft.ja',draft.ja||'','text','required')}${field('英文名','draft.en',draft.en||'','text','required')}<div class="grid2">${field('建议重量 kg（可空）','draft.weight',draft.weight||'','number','min="0" max="2000" step="0.01"')}${field('目标组数','draft.count',draft.count||'3','number','required min="1" max="20" step="1"')}</div>${field('目标次数范围','draft.range',draft.range||'8–12','text','required')}<button class="full" type="submit">保存动作到 ${type} 日</button></form></details>`}
function renderHistory(){const list=getAllNormalizedWorkouts();$('#app').innerHTML=`<div class="eyebrow">YOUR TRAINING ARCHIVE</div><h1>历史记录</h1><button id="open-diagnostics" class="full">数据诊断</button>${recoveryNotice()?`<p class="panel recovery-notice">${esc(recoveryNotice())}</p>`:''}<p class="muted">${list.length} 次训练 · 点击继续记录或生成反馈</p>${list.map(r=>`<button class="history-item" data-history="${r.date}_${r.type}"><div class="row"><strong>${esc(r.date)} · ${r.type} 日</strong><span class="badge">${r.completed?'✓ 已完成':'进行中'}</span></div><p class="muted">${esc(r.gym)||'未填写健身房'}</p></button>`).join('')||'<div class="panel empty">还没有训练记录</div>'}`}
let draft=db.draft||{};
function write(path,value){if(path==='dailyDate'){if(validPlanDate(value)){statusDate=value;render()}return}if(path.startsWith('daily.')){writeDaily(path.slice(6),value);return}if(path.startsWith('draft.')){draft[path.slice(6)]=value;db.draft=draft;save();return}if(path==='date'){if(!/^\d{4}-\d{2}-\d{2}$/.test(value))return;date=value;render();return}if(path==='type'){type=value;draft={};render();return}const r=record();if(r.unrecognized){toast('请先导出数据并查看数据诊断');return}if(path.startsWith('exercises.')||path.startsWith('cardio.'))r.actualTouched=true;if(path==='painAreas'){const a=new Set(r.feedback.painAreas||[]);a.has(value)?a.delete(value):a.add(value);r.feedback.painAreas=[...a]}else{let obj=r;const keys=path.split('.');keys.slice(0,-1).forEach(k=>obj=obj[k]);obj[keys.at(-1)]=value}if(path.startsWith('cardio.'))r.completed=false;if(path==='gym')db.gym=value;if(path.startsWith('exercises.')){const [,i,,j]=path.split('.');r.exercises[i].sets[j].done=false;r.exercises[i].done=false;r.completed=false}r.updated=Date.now();save();updateProgress()}
function refreshPain(){document.querySelectorAll('[data-choice="painAreas"]').forEach(b=>b.setAttribute('aria-pressed',(record().feedback.painAreas||[]).includes(b.dataset.value)))}
$('#app').addEventListener('input',e=>{const el=e.target;if(el.type==='time')el.classList.toggle('time-empty',!el.value);if(!el.dataset.field||el.type==='date')return;if(el.type==='number'&&el.value!==''&&!el.validity.valid)return;write(el.dataset.field,el.value);if(el.dataset.field.startsWith('exercises.')){const set=el.closest('.set');set.classList.remove('done');set.querySelector('[data-set]').textContent='完成本组';set.querySelector('[data-set]').setAttribute('aria-pressed','false');set.querySelector('.counter').textContent='记录本组';const b=el.closest('.exercise').querySelector('[data-exercise]');b.disabled=true;b.textContent='标记动作完成'}});
$('#app').addEventListener('change',e=>{if(e.target.type==='date')write(e.target.dataset.field,e.target.value)});
$('#app').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;if(d.choice){write(d.choice,d.value);if(d.choice==='type')return;b.parentElement.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',x===b));if(d.choice==='painAreas')refreshPain();if(d.choice==='feedback.pain')$('#pain-area').hidden=d.value!=='有';if(d.choice.startsWith('exercises.'))rerenderOpen();}if(d.step){const input=b.parentElement.querySelector('input');const n=Math.max(0,Math.min(Number(input.max),Math.round(((Number(input.value)||0)+Number(d.delta))*100)/100));write(d.step,n);rerenderOpen()}if(d.set){const [i,j]=d.set.split('.'),r=record(),s=r.exercises[i].sets[j];if(!s.done&&(s.weight===''||s.reps===''||Number(s.reps)<1||!s.feel||!s.rir)){toast('请填写重量、次数、体感和 RIR');return}const invalid=b.closest('.set').querySelector('input:invalid');if(invalid){invalid.reportValidity();return}s.done=!s.done;r.exercises[i].done=false;r.completed=false;r.updated=Date.now();save();rerenderOpen()}if(d.exercise){const r=record(),ex=r.exercises[d.exercise];if(ex.sets.every(s=>s.done)){ex.done=!ex.done;r.completed=false;save();render();refreshPain()}}if(d.history){const r=getAllNormalizedWorkouts().find(r=>`${r.date}_${r.type}`===d.history);if(!r)return;date=r.date;type=r.type;view='training';render();refreshPain();scrollTo(0,0)}if(b.id==='finish'){record().completed=true;save();updateProgress();toast('训练已完成，辛苦了！')}if(b.id==='generate')showFeedback('训练反馈',summary())});
function rerenderOpen(){const opened=[...document.querySelectorAll('.exercise')].map(e=>e.open);render();document.querySelectorAll('.exercise').forEach((e,i)=>e.open=opened[i]);refreshPain()}
$('#app').addEventListener('submit',e=>{if(e.target.id!=='add-exercise')return;e.preventDefault();const f=e.target,read=k=>f.querySelector(`[data-field="draft.${k}"]`).value;const ex={cn:read('cn').trim(),ja:read('ja').trim(),en:read('en').trim(),weight:read('weight'),count:Number(read('count')),range:read('range').trim()};if(!ex.cn||!ex.ja||!ex.en||!ex.range)return;db.templates={...(db.templates||{}),[type]:[...templateFor(type),ex]};record().exercises.push({...ex,done:false,sets:Array.from({length:ex.count},()=>({weight:ex.weight,reps:'',feel:'',rir:'',done:false}))});record().completed=false;draft={};db.draft={};save();render();toast('预设动作已保存')});
function summary(){const r=record();if(r.kind==='cardio')return cardioSummary(r);const f=r.feedback;let lines=[`【${Number(date.slice(5,7))}/${Number(date.slice(8))} ${type}日｜${r.gym||'未填写健身房'}】`,`日期：${date}`,`状态：${r.completed?'已完成':'进行中'}`,''];r.exercises.forEach(ex=>{lines.push(ex.cn);ex.sets.forEach(s=>lines.push(`${s.weight===''?'未填':s.weight}×${s.reps||'未填'} ${emoji[s.feel]||'体感未填'} RIR${s.rir||'未填'}${s.done?'':'（未完成）'}`));lines.push('')});lines.push(`总体：${f.overall||'未填'}`,`肌肉刺激：${f.stimulus||'未填'}`,`关节：${f.pain||'未填'}${f.pain==='有'?' · '+((f.painAreas||[]).join(' / ')||'部位未填'):''}`);if(f.notes)lines.push(`备注：${f.notes}`);return lines.join('\n')}
document.querySelector('nav').addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b){view=b.dataset.view;render();if(view==='training')refreshPain();scrollTo(0,0)}});
$('#close-summary').onclick=()=>$('#summary-dialog').close();
$('#copy').onclick=async()=>{const text=$('#summary').value;try{if(!navigator.clipboard?.writeText)throw Error();await navigator.clipboard.writeText(text);$('#copy-status').textContent='✓ 已复制，可以粘贴到 ChatGPT'}catch{const area=$('#summary');area.focus();area.select();area.setSelectionRange(0,area.value.length);let copied=false;try{copied=document.execCommand('copy')}catch{}$('#copy-status').textContent=copied?'✓ 已复制，可以粘贴到 ChatGPT':'请长按上方已选文本，选择“复制”。'}};
window.addEventListener('storage',e=>{if(e.key===KEY&&e.newValue){try{const next=JSON.parse(e.newValue);if(readableRoot(next)){db=next;normalizedCache.clear();Object.keys(workoutDrafts).forEach(k=>delete workoutDrafts[k]);render();if(view==='training')refreshPain();toast('已同步其他窗口的记录')}}catch{}}});
initializeDaily();
render();refreshPain();
if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(()=>toast('离线缓存未就绪，请联网后刷新重试'));

// Layout only: includes the safe-area padding already present in the nav.
const bottomNav = document.querySelector('nav');
function syncNavigationHeight() {
  document.documentElement.style.setProperty('--bottom-nav-height', `${Math.ceil(bottomNav.getBoundingClientRect().height)}px`);
}
syncNavigationHeight();
new ResizeObserver(syncNavigationHeight).observe(bottomNav, {box: 'border-box'});
window.addEventListener('resize', syncNavigationHeight);
window.visualViewport?.addEventListener('resize', () => {
  syncNavigationHeight();
  const focused = document.activeElement;
  if (focused?.matches('main input, main textarea, main select')) {
    requestAnimationFrame(() => focused.scrollIntoView({block: 'nearest'}));
  }
});
