'use strict';
// Additive v1 extension: retain type A/B/C/D; only kind:cardio uses this UI.
const CARDIO_PLANS={
 treadmill:{cn:'跑步机坡度快走',ja:'トレッドミル傾斜ウォーキング',en:'Incline Treadmill Walk',target:'45 min · 10–12% · 4.8–5.2 km/h · RPE 6–7 · 不扶扶手',notes:'保持自然直立，不为了维持坡度而抓扶手。能够说短句，但不适合连续长谈。默认不使用15% / 5 km/h / 60 min高负荷版本；腿部恢复非常好时可自行调整。',minutes:45},
 elliptical:{cn:'椭圆机',ja:'クロストレーナー / エリプティカル',en:'Elliptical Trainer',target:'35–45 min · 中等阻力 · RPE约6',notes:'小腿明显紧、脚踝或膝盖疲劳、跑步机步态不自然时可选。脚掌贴稳踏板，不要把阻力调得太低而只靠惯性滑动。',minutes:40},
 bike:{cn:'立式 / 卧式健身车',ja:'アップライトバイク / リカンベントバイク',en:'Upright Bike / Recumbent Bike',target:'30–45 min · 轻到中等阻力 · RPE 5–6',notes:'整体疲劳明显时选择恢复型方案。保持稳定呼吸，不追速度和高阻力。',minutes:35}
};
function newCardioEntry(plan){return {minutes:CARDIO_PLANS[plan].minutes,incline:plan==='treadmill'?11:'',speed:plan==='treadmill'?'5.0':'',resistance:'',rpe:'',handrails:'否',feel:'',legFatigue:'',pain:'',notes:''}}
function cardioPlans(r){if(!r.plan?.cardioOptions)return CARDIO_PLANS;return Object.fromEntries(r.plan.cardioOptions.map(e=>[e.id,{cn:e.nameZh,ja:e.nameJa,en:e.nameEn,minutes:e.durationMin,target:`${e.durationMin} min · ${e.id==='treadmill'?`${e.inclineMin}–${e.inclineMax}% · ${e.speedMin}–${e.speedMax} km/h`:`阻力：${e.resistance||'现场填写'}`} · RPE ${e.targetRpeMin}–${e.targetRpeMax}`,notes:e.instructions}]))}
function cardioEntryForRecord(r,id){const entry=newCardioEntry(id);const e=r.plan?.cardioOptions?.find(e=>e.id===id);if(e){entry.minutes=e.durationMin;entry.resistance=e.resistance||'';if(id==='treadmill'){entry.incline=e.inclineMin;entry.speed=String(e.speedMin)}}return entry}
function newCardioRecord(day,gym){return {date:day,type:'D',kind:'cardio',gym,exercises:[],feedback:{},completed:false,cardio:{selected:'treadmill',entries:{treadmill:newCardioEntry('treadmill')}}}}
function activeCardio(r=record()){return r.cardio.entries[r.cardio.selected]}
function cardioValid(r){const c=activeCardio(r),n=v=>v!==''&&Number.isFinite(Number(v));return n(c.minutes)&&c.minutes>0&&c.minutes<=300&&n(c.rpe)&&c.rpe>=1&&c.rpe<=10&&['否','是'].includes(c.handrails)&&['easy','normal','hard','max'].includes(c.feel)&&n(c.legFatigue)&&c.legFatigue>=1&&c.legFatigue<=5&&['无','有'].includes(c.pain)&&(r.cardio.selected==='treadmill'?n(c.incline)&&c.incline>=0&&c.incline<=40&&n(c.speed)&&c.speed>0&&c.speed<=30:String(c.resistance).trim().length>0)}
function cardioProgress(){const r=record();$('#progress').max=1;$('#progress').value=r.completed?1:0;$('#progress-text').textContent=r.completed?'1 / 1 方案 · 已完成':'0 / 1 方案';$('#finish-cardio').disabled=!cardioValid(r);$('#finish-cardio').textContent=r.completed?'✓ D日已完成':'完成 D 日'}
function cardioStepper(label,key,value,delta,max){const path=`cardio.entries.${record().cardio.selected}.${key}`;return `<label>${label}</label><div class="stepper"><button data-cstep="${key}" data-delta="-${delta}" aria-label="减少${label}">−${delta}</button><input data-field="${path}" aria-label="${label}" type="number" inputmode="${key==='minutes'?'numeric':'decimal'}" min="0" max="${max}" step="${key==='minutes'?1:0.1}" value="${esc(value)}"><button data-cstep="${key}" data-delta="${delta}" aria-label="增加${label}">+${delta}</button></div>`}
function renderCardio(){const r=record(),p=cardioPlans(r)[r.cardio.selected],c=activeCardio(r),prefix=`cardio.entries.${r.cardio.selected}.`;
 $('#app').innerHTML=`<div class="row"><div><div class="eyebrow">CARDIO & RECOVERY</div><h1>${date===today()?'今日训练':'训练记录'}</h1></div><span class="badge">D DAY</span></div><section class="panel session"><div class="grid2">${field('训练日期','date',date,'date')}${field('健身房','gym',r.gym)}</div><label>训练类型</label>${choices('type',['A','B','C','D'],type)}<div class="row progress-label"><span>完成进度</span><span id="progress-text"></span></div><progress id="progress" aria-label="有氧完成进度"></progress></section>${planContext(r)}<div class="section-title"><h2>有氧 / 恢复</h2></div><section class="exercise"><div class="names"><h3>${esc(p.cn)}</h3><small lang="ja">${esc(p.ja)}</small><small lang="en">${esc(p.en)}</small></div><p class="target">${esc(p.target)}</p><p class="muted imported-instructions">${esc(p.notes)}</p><button class="full" id="cardio-alternatives" aria-expanded="false">改用低冲击方案</button><div id="cardio-options" hidden><p class="muted">只需完成一个方案。切换会保留各方案已填数据，完成状态需重新确认。</p>${Object.entries(cardioPlans(r)).map(([k,v])=>`<button class="full" data-cplan="${k}" aria-pressed="${k===r.cardio.selected}">${esc(v.cn)}</button>`).join('')}</div><div class="set">${cardioStepper('实际时间（分钟）','minutes',c.minutes,5,300)}${r.cardio.selected==='treadmill'?cardioStepper('平均 / 主要坡度（%）','incline',c.incline,1,40)+cardioStepper('实际速度（km/h）','speed',c.speed,0.1,30):field('实际阻力（档位或描述）',prefix+'resistance',c.resistance)}<label>RPE · 1–10</label>${choices(prefix+'rpe',Array.from({length:10},(_,i)=>String(i+1)),c.rpe,5)}<label>是否扶扶手</label>${choices(prefix+'handrails',['否','是'],c.handrails)}<label>体感</label>${choices(prefix+'feel',feelings,c.feel,2)}<label>腿部疲劳 · 1–5</label>${choices(prefix+'legFatigue',['1','2','3','4','5'],c.legFatigue)}<label>关节 / 疼痛</label>${choices(prefix+'pain',['无','有'],c.pain)}<label>备注<textarea data-field="${prefix}notes">${esc(c.notes)}</textarea></label><button id="finish-cardio" class="primary full"></button><button id="generate" class="full">生成训练反馈 ↗</button></div></section>`;cardioProgress()
}
function cardioSummary(r){const c=activeCardio(r),p=cardioPlans(r)[r.cardio.selected];return [`【${Number(r.date.slice(5,7))}/${Number(r.date.slice(8))} D日｜${r.gym||'未填写健身房'}】`,`日期：${r.date}`,`状态：${r.completed?'已完成':'进行中'}`,'',p.cn,r.cardio.selected==='treadmill'?`${c.minutes||'未填'}min｜${c.incline===''?'未填':c.incline}%｜${c.speed===''?'未填':Number(c.speed).toFixed(1)}km/h`:`${c.minutes||'未填'}min｜阻力：${c.resistance||'未填'}`,`RPE${c.rpe||'未填'}｜扶手：${c.handrails||'未填'}`,`体感：${({easy:'🟢轻松',normal:'🟡普通',hard:'🟠困难',max:'🔴极限'})[c.feel]||'未填'}`,`腿部疲劳：${c.legFatigue||'未填'}/5`,'',`关节：${c.pain||'未填'}`,`备注：${c.notes||''}`].join('\n')}
document.addEventListener('click',event=>{const b=event.target.closest('#app button');if(!b)return;
 if(b.id==='cardio-alternatives'){const panel=document.querySelector('#cardio-options');panel.hidden=!panel.hidden;b.setAttribute('aria-expanded',!panel.hidden)}
 if(b.dataset.cplan){const r=record(),id=b.dataset.cplan;if(id===r.cardio.selected)return;r.cardio.entries[id]??=cardioEntryForRecord(r,id);r.cardio.selected=id;r.completed=false;r.updated=Date.now();save();render()}
 if(b.dataset.cstep){const input=b.parentElement.querySelector('input');const value=Math.max(0,Math.min(Number(input.max),Math.round((Number(input.value)+Number(b.dataset.delta))*10)/10));write(input.dataset.field,value);render()}
 if(b.id==='finish-cardio'){const r=record();const invalid=document.querySelector('#app input:invalid');if(invalid){invalid.reportValidity();return}if(!cardioValid(r))return;r.completed=true;r.updated=Date.now();save();cardioProgress();toast('D日已完成，辛苦了！')}
});
