'use strict';
const DAILY_FIELDS=[['上床时间','bedtime','time','bed'],['预计入睡时间','sleepTime','time','asleep'],['夜间醒来次数','nightAwakenings','number','wakes'],['最终起床时间','wakeTime','time','wake'],['估计总睡眠时长（小时）','estimatedSleepHours','number','hours'],['午睡时间（分钟）','napMinutes','number','nap'],['咖啡因最后摄入时间','lastCaffeineTime','time','caffeine']];
const DAILY_RATINGS=[['起床精神','wakeEnergy'],['上午专注','morningFocus'],['下午专注','afternoonFocus'],['肌肉酸痛','muscleSoreness'],['训练意愿','trainingMotivation'],['当天整体困倦','daytimeSleepiness']];
function emptyDaily(day){return {date:day,bedtime:'',sleepTime:'',nightAwakenings:null,wakeTime:'',estimatedSleepHours:null,napMinutes:0,lastCaffeineTime:'',wakeEnergy:null,morningFocus:null,afternoonFocus:null,muscleSoreness:null,trainingMotivation:null,daytimeSleepiness:null,notes:'',updatedAt:null}}
function migrateDaily(data){const next={...data,dailyStatusByDate:{...(data.dailyStatusByDate||{})}};for(const [day,s]of Object.entries(data.sleep||{})){if(!validPlanDate(day)||!isObject(s))continue;const existing=next.dailyStatusByDate[day];const d=isObject(existing)?{...existing}:emptyDaily(day);d.date??=day;for(const [,key,type,legacy]of DAILY_FIELDS){const value=s[legacy];if(missingValue(d[key])||(!existing&&key==='napMinutes')){if(!missingValue(value)){if(type!=='number')d[key]=String(value);else if(Number.isFinite(Number(value)))d[key]=Number(value)}}}DAILY_RATINGS.forEach(([,key],i)=>{const v=s['rating'+i];if(missingValue(d[key])&&!missingValue(v)&&Number(v)>=1&&Number(v)<=5)d[key]=Number(v)});if(missingValue(d.notes)&&typeof s.notes==='string')d.notes=s.notes;next.dailyStatusByDate[day]=d}return next}
function commitData(next){if(blocked){toast('本地存储不可用，未保存');return false}try{localStorage.setItem(KEY,JSON.stringify(next));db=next;$('#save-status').textContent='● 已自动保存';return true}catch{toast('保存失败，原存储未清除，请释放空间后重试');return false}}
function initializeDaily(){if(blocked||!storageSnapshot().exists)return;const next=migrateDaily(db);if(JSON.stringify(next)!==JSON.stringify(db))commitData(next)}
function dailyComplete(d){return d.estimatedSleepHours!==null&&d.estimatedSleepHours!==undefined&&d.estimatedSleepHours!==''&&DAILY_RATINGS.every(([,k])=>d[k]>=1&&d[k]<=5)}
function currentDaily(){return db.dailyStatusByDate?.[statusDate]||emptyDaily(statusDate)}
function updateDailyBadge(){const badge=document.querySelector('#daily-completeness');if(badge)badge.textContent=dailyComplete(currentDaily())?'已完整':'未完整'}
function writeDaily(key,value){const d={...currentDaily(),[key]:value,updatedAt:new Date().toISOString()};if(DAILY_RATINGS.some(([,k])=>k===key)||DAILY_FIELDS.some(([,k,t])=>k===key&&t==='number'))d[key]=value===''?null:Number(value);if(commitData({...db,dailyStatusByDate:{...(db.dailyStatusByDate||{}),[statusDate]:d}}))updateDailyBadge()}
function renderDailyStatus(){const d=currentDaily();$('#app').innerHTML=`<div class="eyebrow">DAILY STATUS</div><div class="row"><h1>每日状态</h1><span id="daily-completeness" class="badge">${dailyComplete(d)?'已完整':'未完整'}</span></div><p class="muted">记录今天的睡眠、精力与恢复状态。建议晚上完成。</p><section class="panel sleep-fields">${field('记录日期','dailyDate',statusDate,'date')}<h2>睡眠</h2><div class="grid2">${DAILY_FIELDS.map(([l,k,t])=>field(l,'daily.'+k,d[k]??'',t,t==='number'?`inputmode="${k==='estimatedSleepHours'?'decimal':'numeric'}" min="0" max="${k==='estimatedSleepHours'?24:k==='napMinutes'?1440:99}" step="${k==='estimatedSleepHours'?0.1:1}"`:'')).join('')}</div></section><section class="panel"><h2>每日状态</h2>${DAILY_RATINGS.map(([l,k],i)=>`<label>${l}</label>${choices('daily.'+k,['1','2','3','4','5'],d[k])}<div class="rating-ends"><span>1 · ${[3,5].includes(i)?'无 / 低':'很低'}</span><span>5 · ${[3,5].includes(i)?'强 / 高':'很好 / 很高'}</span></div>`).join('')}<label>备注<textarea data-field="daily.notes">${esc(d.notes)}</textarea></label><button id="generate-daily" class="primary full">生成今日状态反馈</button></section>`}
function dailySummary(){const d=currentDaily(),v=(k,suffix='')=>d[k]==null||d[k]===''?'未填':`${d[k]}${suffix}`;return [`【${Number(statusDate.slice(5,7))}/${Number(statusDate.slice(8))} 每日状态】`,`日期：${statusDate}`,'','睡眠：',`上床：${v('bedtime')}`,`入睡：${v('sleepTime')}`,`夜醒：${v('nightAwakenings','次')}`,`起床：${v('wakeTime')}`,`总睡眠：${v('estimatedSleepHours','h')}`,`午睡：${v('napMinutes','min')}`,`最后咖啡因：${v('lastCaffeineTime')}`,'','状态：',...DAILY_RATINGS.map(([l,k])=>`${l==='当天整体困倦'?'整体困倦':l}：${v(k,'/5')}`),'',`备注：${d.notes||''}`].join('\n')}
function showFeedback(title,text){$('#summary-dialog h2').textContent=title;$('#summary').value=text;$('#copy-status').textContent='';$('#summary-dialog').showModal()}
