'use strict';
function validPlanDate(s){if(typeof s!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(s)||s<'1900-01-01'||s>'2199-12-31')return false;const d=new Date(s+'T00:00:00Z');return Number.isFinite(d.getTime())&&d.toISOString().slice(0,10)===s}
function parseTrainingPlan(text){
 if(text.length>100000)throw Error('计划过长，请限制在100KB以内');let p;try{p=JSON.parse(text)}catch{throw Error('不是有效 JSON，请只粘贴 JSON，不要包含代码围栏或解释文字')}
 const object=(x,label)=>{if(!x||typeof x!=='object'||Array.isArray(x))throw Error(label+'必须是对象')};
 const keys=(x,allowed,label)=>{object(x,label);for(const key of Object.keys(x))if(!allowed.includes(key))throw Error(label+'包含不支持的字段：'+key)};
 const string=(v,label,max=200,empty=false)=>{if(typeof v!=='string'||(!empty&&!v.trim())||v.length>max)throw Error(label+'必须为'+(empty?'':'非空')+'字符串，最多'+max+'字');return v.trim()};
 const number=(v,label,min,max,integer=false)=>{if(typeof v!=='number'||!Number.isFinite(v)||v<min||v>max||(integer&&!Number.isInteger(v)))throw Error(label+`必须为${min}–${max}之间的${integer?'整数':'数字'}`);return v};
 const names=(x,label)=>({nameZh:string(x.nameZh,label+'缺少或无效的中文名称'),nameJa:string(x.nameJa,label+'缺少或无效的日文名称'),nameEn:string(x.nameEn,label+'缺少或无效的英文名称')});
 const range=(a,b,label)=>{if(a>b)throw Error(label+'最小值不能大于最大值')};
 keys(p,['schema','version','date','type','kind','gym','title','notes','exercises','cardioOptions'],'计划');
 if(p.schema!=='haoxuan-training-plan')throw Error('schema 必须为 haoxuan-training-plan');if(p.version!==1)throw Error('计划 version 必须为1');if(!validPlanDate(p.date))throw Error('训练日期格式错误或日期不存在');if(!['A','B','C','D'].includes(p.type))throw Error('type 必须为 A/B/C/D');if(!['strength','cardio'].includes(p.kind))throw Error('kind 必须为 strength 或 cardio');
 const result={schema:p.schema,version:1,date:p.date,type:p.type,kind:p.kind,gym:string(p.gym,'健身房'),title:p.title===undefined?'':string(p.title,'标题',200,true),notes:p.notes===undefined?'':string(p.notes,'备注',5000,true)};
 if(p.kind==='strength'){
  if(p.cardioOptions!==undefined)throw Error('力量计划不能包含 cardioOptions');if(!Array.isArray(p.exercises)||p.exercises.length<1||p.exercises.length>30)throw Error('力量计划须有1–30个动作');
  result.exercises=p.exercises.map((e,i)=>{const label=`第${i+1}个动作`;keys(e,['nameZh','nameJa','nameEn','weight','weightUnit','weightMode','sets','repMin','repMax','restSeconds','instructions'],label);const n=names(e,label);if(e.weightUnit!=='kg')throw Error(label+'的 weightUnit 必须为 kg');if(!['machine','total','per-side','bodyweight'].includes(e.weightMode))throw Error(label+'的 weightMode 无效');const x={...n,weight:e.weight===null?null:number(e.weight,label+'建议重量',0,2000),weightUnit:'kg',weightMode:e.weightMode,sets:number(e.sets,label+'组数',1,20,true),repMin:number(e.repMin,label+' repMin',1,999,true),repMax:number(e.repMax,label+' repMax',1,999,true),restSeconds:e.restSeconds===undefined?0:number(e.restSeconds,label+'休息秒数',0,3600,true),instructions:e.instructions===undefined?'':string(e.instructions,label+'说明',5000,true)};range(x.repMin,x.repMax,label+' repMin / repMax');return x});
 }else{
  if(p.type!=='D')throw Error('有氧计划的 type 必须为 D');if(p.exercises!==undefined)throw Error('有氧计划不能包含 exercises');if(!Array.isArray(p.cardioOptions)||p.cardioOptions.length<1||p.cardioOptions.length>3)throw Error('有氧计划须有1–3个方案');const ids=new Set();
  result.cardioOptions=p.cardioOptions.map((e,i)=>{const label=`第${i+1}个有氧方案`;keys(e,['id','nameZh','nameJa','nameEn','durationMin','inclineMin','inclineMax','speedMin','speedMax','targetRpeMin','targetRpeMax','resistance','instructions'],label);if(!['treadmill','elliptical','bike'].includes(e.id)||ids.has(e.id))throw Error(label+' id 必须为不重复的 treadmill / elliptical / bike');ids.add(e.id);const x={id:e.id,...names(e,label),durationMin:number(e.durationMin,label+'分钟',1,300,true),targetRpeMin:number(e.targetRpeMin,label+'目标RPE',1,10),targetRpeMax:number(e.targetRpeMax,label+'目标RPE',1,10),resistance:e.resistance===undefined?'':string(e.resistance,label+'阻力',200,true),instructions:e.instructions===undefined?'':string(e.instructions,label+'说明',5000,true)};range(x.targetRpeMin,x.targetRpeMax,label+' RPE');if(e.id==='treadmill'){for(const k of ['inclineMin','inclineMax','speedMin','speedMax'])x[k]=number(e[k],label+' '+k,k.startsWith('speed')?0.1:0,k.startsWith('speed')?30:40);range(x.inclineMin,x.inclineMax,label+'坡度');range(x.speedMin,x.speedMax,label+'速度')}else if(['inclineMin','inclineMax','speedMin','speedMax'].some(k=>e[k]!==undefined))throw Error(label+'不是跑步机，不支持坡度或速度字段');return x});
 }
 return result;
}
function importedRecord(p){const r={date:p.date,type:p.type,kind:p.kind,gym:p.gym,exercises:[],feedback:{},completed:false,planSource:'chatgpt-import',importedAt:new Date().toISOString(),plan:JSON.parse(JSON.stringify(p))};if(p.kind==='strength')r.exercises=p.exercises.map(e=>({cn:e.nameZh,ja:e.nameJa,en:e.nameEn,weight:e.weight??'',recommendedWeight:e.weight,weightMode:e.weightMode,restSeconds:e.restSeconds,instructions:e.instructions,count:e.sets,range:`${e.repMin}–${e.repMax}`,done:false,sets:Array.from({length:e.sets},()=>({weight:e.weight??'',reps:'',feel:'',rir:'',done:false}))}));else{const first=p.cardioOptions[0].id;r.cardio={selected:first,entries:{[first]:cardioEntryForRecord(r,first)}}}return r}
function hasActualWorkout(r){
 if(!r)return false;if(r.completed||r.actualTouched||r.updated)return true;
 if(Object.values(r.feedback||{}).some(v=>Array.isArray(v)?v.length:v!==''&&v!=null))return true;
 if(r.kind==='cardio'){
  if(!r.cardio||!r.cardio.entries)return true;
  for(const [id,e]of Object.entries(r.cardio.entries)){if(!Object.hasOwn(cardioPlans(r),id))return true;const defaults=cardioEntryForRecord(r,id);if(Object.keys(e).some(k=>String(e[k]??'')!==String(defaults[k]??'')))return true}return false;
 }
 if(!Array.isArray(r.exercises))return true;return r.exercises.some(e=>e.done||!Array.isArray(e.sets)||e.sets.length!==e.count||e.sets.some(s=>s.done||s.reps!==''||s.rir!==''||s.feel!==''||s.actualWeight!=null||String(s.weight)!==String(e.recommendedWeight??e.weight)));
}
let pendingPlan=null,previewTarget=null;
function latestImportData(){if(blocked)throw Error('本地存储不可用，无法导入');const raw=localStorage.getItem(KEY);const next=raw?JSON.parse(raw):db;if(next.version!==1||!next.records||!next.templates)throw Error('现有数据无法读取，停止导入');return next}
function importPreview(p){const name=e=>`<h3>${esc(e.nameZh)}</h3><p class="muted">${esc(e.nameJa)} · ${esc(e.nameEn)}</p>`;return `<h3>${p.date} · ${p.type} DAY</h3><p>${esc(p.gym)}</p><h3>${esc(p.title)}</h3><p class="muted">${esc(p.notes)}</p><p>${p.kind==='strength'?`${p.exercises.length}个动作 · 共${p.exercises.reduce((n,e)=>n+e.sets,0)}组`:`${p.cardioOptions.length}个有氧方案 · 只需完成一个`}</p>${p.kind==='strength'?p.exercises.map(e=>`<section class="panel">${name(e)}<p>${e.weight===null?'重量待填':e.weight+'kg'} · ${e.sets}×${e.repMin}–${e.repMax}</p><p class="muted">${esc(e.weightMode)} · 休息${e.restSeconds}秒<br>${esc(e.instructions)}</p></section>`).join(''):p.cardioOptions.map(e=>`<section class="panel">${name(e)}<p>${e.durationMin}min · RPE${e.targetRpeMin}–${e.targetRpeMax}</p>${e.id==='treadmill'?`<p>${e.inclineMin}–${e.inclineMax}% · ${e.speedMin}–${e.speedMax}km/h</p>`:`<p>阻力：${esc(e.resistance)||'现场填写'}</p>`}<p class="muted">${esc(e.instructions)}</p></section>`).join('')}`}
function sizeImportDialog(){const d=document.querySelector('#import-dialog');if(!d?.open)return;const v=window.visualViewport;d.style.top=`${(v?.offsetTop||0)+8}px`;d.style.maxHeight=`${Math.max(140,(v?.height||innerHeight)-16)}px`}
function openImporter(){pendingPlan=null;$('#import-preview').hidden=true;$('#import-editor').hidden=false;$('#import-error').textContent='';$('#import-dialog').showModal();sizeImportDialog()}
function parseImport(){try{const p=parseTrainingPlan($('#plan-json').value);const data=latestImportData(),r=data.records[`${p.date}_${p.type}`];pendingPlan=p;previewTarget=JSON.stringify(r??null);$('#import-preview-content').innerHTML=importPreview(p);$('#import-conflict').textContent=hasActualWorkout(r)?'该日期已有训练数据，无法覆盖。':r?'当天已有未开始计划，是否替换？':'确认后将保存此计划。';$('#confirm-import').disabled=hasActualWorkout(r);$('#confirm-import').textContent=r?'确认替换并导入':'确认导入';$('#import-editor').hidden=true;$('#import-preview').hidden=false;$('#import-error').textContent='';$('#import-scroll').scrollTop=0}catch(e){pendingPlan=null;$('#import-error').textContent=e.message}}
function confirmImport(){try{if(!pendingPlan)return;const p=pendingPlan,data=latestImportData(),id=`${p.date}_${p.type}`,r=data.records[id];if(hasActualWorkout(r))throw Error('该日期已有训练数据，无法覆盖。');if(JSON.stringify(r??null)!==previewTarget)throw Error('目标记录已在其他窗口变化，请返回重新解析并确认');const next={...data,records:{...data.records,[id]:importedRecord(p)}};if(!commitData(next))return;pendingPlan=null;delete workoutDrafts[id];date=p.date;type=p.type;view='training';$('#import-dialog').close();render();scrollTo(0,0);toast('训练计划已导入')}catch(e){$('#import-error').textContent=e.message;$('#confirm-import').disabled=true}}
function planContext(r){return r.plan?`<section class="panel imported-plan"><h2>${esc(r.plan.title)||'导入计划'}</h2><p class="muted">${esc(r.plan.notes)}</p></section>`:''}
function importedExerciseInfo(e){return e.weightMode?`<p class="muted imported-instructions">重量方式：${esc(({machine:'机器显示重量',total:'总重量','per-side':'单侧重量',bodyweight:'自重 / 附加重量'})[e.weightMode])} · 休息${e.restSeconds}秒<br>${esc(e.instructions)}</p>`:''}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.id==='open-import')openImporter();if(b.id==='cancel-import')$('#import-dialog').close();if(b.id==='parse-import')parseImport();if(b.id==='edit-import'){$('#import-preview').hidden=true;$('#import-editor').hidden=false;pendingPlan=null;$('#import-error').textContent=''}if(b.id==='confirm-import')confirmImport();if(b.id==='generate-daily')showFeedback('今日状态反馈',dailySummary())});
window.visualViewport?.addEventListener('resize',sizeImportDialog);window.visualViewport?.addEventListener('scroll',sizeImportDialog);window.addEventListener('resize',sizeImportDialog);
