const {chromium,webkit}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=path.join(__dirname,'..'),url=process.env.TEST_URL||'http://127.0.0.1:8765',KEY='haoxuan-training-log:v1';
const full=JSON.parse(fs.readFileSync(path.join(root,'examples/health-sleep-full.json'),'utf8')),minimal=JSON.parse(fs.readFileSync(path.join(root,'examples/health-sleep-minimal.json'),'utf8'));
(async()=>{for(const [name,engine]of [['chromium',chromium],['webkit',webkit]]){const browser=await engine.launch(),ctx=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:'block'}),p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(url);
await p.evaluate(key=>{const actual={date:'2026-09-06',type:'C',gym:'成増',completed:true,exercises:[{cn:'腿举',ja:'レッグプレス',en:'Leg Press',weight:42.5,count:1,range:'8–12',done:true,sets:[{weight:47,reps:12,rir:2,feel:'normal',done:true}]}],feedback:{notes:'保存历史'}};db={version:1,templates:{A:[],B:[],C:[],D:[]},records:{'2026-09-06_C':actual},sleep:{},dailyStatusByDate:{'2026-09-09':{...emptyDaily('2026-09-09'),afternoonFocus:4,notes:'旧记录'}}};localStorage.setItem(key,JSON.stringify(db));statusDate='2026-09-09';view='sleep';render()},KEY);
const raw=()=>p.evaluate(k=>localStorage.getItem(k),KEY),before=await raw();
// Pure parser/merge checks: no storage paths are invoked.
const results=await p.evaluate(({full,minimal})=>{const parse=x=>parseHealthSleep(JSON.stringify(x)),p=parse(full),m=parse(minimal),empty=emptyDaily(p.date),manual={...empty,sleepTime:'01:15',nightAwakenings:0,estimatedSleepHours:8,napMinutes:20,lastCaffeineTime:'13:00',wakeEnergy:1,morningFocus:2,afternoonFocus:3,muscleSoreness:4,trainingMotivation:5,daytimeSleepiness:2,notes:'保留'};const invalid=[];function bad(label,change){const f=structuredClone(full);change(f);try{parse(f);invalid.push(label)}catch{}}for(const [k,v]of [['schema','bad'],['version',2],['date','2026-02-30'],['source','unknown'],['sleep',[]]])bad(k,p=>p[k]=v);for(const [k,v]of [['totalSleepMinutes',-1],['totalSleepMinutes',901],['deepMinutes',-1],['deepMinutes',901],['awakeEpisodeCount',1.1],['awakeEpisodeCount',101],['coreMinutes','90'],['awakeMinutes',-1],['inBedMinutes',-1]])bad(k,p=>p.sleep[k]=v);for(const value of ['2026-09-10T01:05:00','2026-02-30T01:00:00+09:00','2026-09-10T24:00:00+09:00','2026-09-10T01:00:00+14:30'])bad(value,p=>p.sleep.firstSleepStart=value);bad('wake chronology',p=>p.sleep.finalWakeTime=p.sleep.firstSleepStart);bad('window chronology',p=>p.dataWindowEnd=p.dataWindowStart);for(const text of ['x','{"schema":','{"schema":"haoxuan-health-sleep",}',JSON.stringify(full).replace('440','1e999')]){try{parseHealthSleep(text);invalid.push(text)}catch{}}
const warn=structuredClone(full);warn.sleep.totalSleepMinutes=400;warn.sourceNames=['Apple Watch','iPhone'];const noHealth=dailySummary();const expected=['【9/9 每日状态】','日期：2026-09-09','','睡眠：','上床：未填','入睡：未填','夜醒：未填','起床：未填','总睡眠：未填','午睡：0min','最后咖啡因：未填','','状态：','起床精神：未填','上午专注：未填','下午专注：4/5','肌肉酸痛：未填','训练意愿：未填','整体困倦：未填','','备注：旧记录'].join('\n');return {invalid,complete:mergeHealthSleep(empty,p,false,'fixed'),kept:mergeHealthSleep(manual,p,false,'fixed'),replaced:mergeHealthSleep(manual,p,true,'fixed'),nulls:m.sleep,warning:parse(warn).warnings,emptyWarnings:m.warnings,fence:parseHealthSleep('```json\n'+JSON.stringify(full)+'\n```').date,bom:parseHealthSleep('\uFEFF '+JSON.stringify(full)).date,oldSummaryUnchanged:noHealth===expected}}, {full,minimal});
assert.deepEqual(results.invalid,[]);assert.equal(results.complete.bedtime,'00:30');assert.equal(results.complete.sleepTime,'01:05');assert.equal(results.complete.wakeTime,'09:00');assert.equal(results.complete.estimatedSleepHours,440/60);assert.equal(results.complete.nightAwakenings,2);assert.equal(results.kept.sleepTime,'01:15');assert.equal(results.kept.nightAwakenings,0);assert.equal(results.replaced.sleepTime,'01:05');assert.equal(results.replaced.nightAwakenings,2);for(const k of ['wakeEnergy','morningFocus','afternoonFocus','muscleSoreness','trainingMotivation','daytimeSleepiness','notes','lastCaffeineTime','napMinutes'])assert.deepEqual(results.kept[k],results.replaced[k]);assert.equal(results.nulls.awakeEpisodeCount,null);assert.equal(results.nulls.remMinutes,null);assert.equal(results.warning.length,2);assert.equal(results.emptyWarnings.length,0);assert(results.oldSummaryUnchanged);assert.equal(await raw(),before);
// Opening doesn't touch the clipboard. Denied/unavailable reads reveal paste fallback.
await p.evaluate(()=>{window.clipboardReads=0;Object.defineProperty(navigator,'clipboard',{configurable:true,value:{readText:async()=>{window.clipboardReads++;throw Error('denied')}}})});await p.locator('#open-health').click();assert.equal(await p.evaluate(()=>clipboardReads),0);await p.locator('#health-clipboard').click();await p.locator('#health-manual').waitFor({state:'visible'});assert.match(await p.locator('#health-error').textContent(),/长按/);await p.locator('#health-json').fill('not json');await p.locator('#parse-health').click();assert.equal(await raw(),before);assert.match(await p.locator('#health-error').textContent(),/无法解析/);await p.locator('#close-health').click();
await p.evaluate(json=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{readText:async()=>json}}),JSON.stringify(full));await p.locator('#open-health').click();await p.locator('#health-clipboard').click();await p.locator('#health-preview').waitFor({state:'visible'});assert.match(await p.locator('#health-preview-content').textContent(),/此睡眠记录属于 2026\/09\/10/);assert.match(await p.locator('#confirm-health').textContent(),/切换到9\/10/);assert.equal(await raw(),before);await p.locator('#confirm-health').click();const imported=JSON.parse(await raw());assert.deepEqual(imported.records,JSON.parse(before).records);assert.deepEqual(imported.dailyStatusByDate['2026-09-09'],JSON.parse(before).dailyStatusByDate['2026-09-09']);assert.equal(imported.dailyStatusByDate['2026-09-10'].healthSleep.totalSleepMinutes,440);assert.equal(await p.locator('[data-field=dailyDate]').inputValue(),'2026-09-10');assert.match(await p.evaluate(()=>dailySummary()),/Apple Health：\n总睡眠：7h20m/);assert.equal(await p.locator('[data-field="daily.estimatedSleepHours"]').evaluate(e=>e.checkValidity()),true);
// Reimport requires confirmation, defaults protected; stale target blocks confirmation.
await p.locator('[data-field="daily.sleepTime"]').fill('01:15');await p.locator('[data-field="daily.notes"]').fill('主观备注不动');await p.locator('#open-health').click();await p.locator('#health-clipboard').click();await p.locator('#health-preview').waitFor({state:'visible'});assert.match(await p.locator('#confirm-health').textContent(),/使用新 Apple Health 数据替换/);const reimportRaw=await raw();await p.locator('#close-health').click();assert.equal(await raw(),reimportRaw);await p.locator('#open-health').click();await p.locator('#health-clipboard').click();await p.locator('#health-preview').waitFor({state:'visible'});await p.locator('#confirm-health').click();assert.equal(JSON.parse(await raw()).dailyStatusByDate['2026-09-10'].sleepTime,'01:15');
await p.locator('#open-health').click();await p.locator('#health-clipboard').click();await p.locator('#health-preview').waitFor({state:'visible'});await p.locator('#replace-health-fields').click();await p.locator('#confirm-health').click();let d=JSON.parse(await raw()).dailyStatusByDate['2026-09-10'];assert.equal(d.sleepTime,'01:05');assert.equal(d.notes,'主观备注不动');
await p.locator('#open-health').click();await p.locator('#health-clipboard').click();await p.locator('#health-preview').waitFor({state:'visible'});await p.evaluate(k=>{const d=JSON.parse(localStorage.getItem(k));d.dailyStatusByDate['2026-09-10'].notes='另一个页面的新备注';localStorage.setItem(k,JSON.stringify(d))},KEY);const changed=await raw();await p.locator('#confirm-health').click();assert.equal(await raw(),changed);assert.match(await p.locator('#health-error').textContent(),/已变化/);await p.locator('#close-health').click();
// Missing stages render dashes, never synthetic zeros. Removal keeps filled fields.
await p.evaluate(()=>{db=storageSnapshot().data;render()});p.once('dialog',dialog=>dialog.accept());await p.locator('#remove-health').click();d=JSON.parse(await raw()).dailyStatusByDate['2026-09-10'];assert(!d.healthSleep);assert.equal(d.sleepTime,'01:05');assert.equal(d.notes,'另一个页面的新备注');
await p.evaluate(json=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{readText:async()=>json}}),JSON.stringify(minimal));await p.locator('#open-health').click();await p.locator('#health-clipboard').click();await p.locator('#health-preview').waitFor({state:'visible'});assert.match(await p.locator('#health-preview-content').textContent(),/REM—/);await p.locator('#confirm-health').click();assert.equal(JSON.parse(await raw()).dailyStatusByDate['2026-09-10'].nightAwakenings,2,'null episode count does not erase previous count');
// An unrelated concurrent change must be preserved by confirmation's fresh read.
await p.locator('#open-health').click();await p.locator('#health-clipboard').click();await p.locator('#health-preview').waitFor({state:'visible'});await p.evaluate(k=>{const r=JSON.parse(localStorage.getItem(k));r.dailyStatusByDate['2026-09-09'].notes='其他日期最新值';localStorage.setItem(k,JSON.stringify(r))},KEY);await p.locator('#confirm-health').click();assert.equal(JSON.parse(await raw()).dailyStatusByDate['2026-09-09'].notes,'其他日期最新值');
// A delayed clipboard promise must never resurrect a closed sheet or replace a new manual draft.
await p.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{readText:()=>new Promise(resolve=>window.resolveClipboard=resolve)}}));await p.locator('#open-health').click();await p.locator('#health-clipboard').click();await p.locator('#close-health').click();await p.evaluate(text=>window.resolveClipboard(text),JSON.stringify(full));assert.equal(await p.locator('#health-dialog').isVisible(),false);await p.locator('#open-health').click();await p.locator('#health-clipboard').click();await p.locator('#health-paste').click();await p.locator('#health-json').fill('manual draft');await p.evaluate(text=>window.resolveClipboard(text),JSON.stringify(full));assert.equal(await p.locator('#health-json').inputValue(),'manual draft');assert.equal(await p.locator('#health-preview').isVisible(),false);await p.locator('#close-health').click();
const scan=async()=>{const bad=await p.evaluate(()=>[...document.querySelectorAll('*')].filter(e=>e.getClientRects().length).filter(e=>{const r=e.getBoundingClientRect();return r.width&&(r.left < -1||r.right>document.documentElement.clientWidth+1)}).map(e=>e.tagName+'#'+e.id));assert.deepEqual(bad,[])};
for(const [width,height]of [[320,568],[375,667],[390,844],[393,852],[430,932]]){await p.setViewportSize({width,height});await p.addStyleTag({content:'html,body{overflow-x:visible!important}'});await p.locator('[data-view=sleep]').click();await scan();const controls=await p.locator('.sleep-fields input').evaluateAll(es=>es.every(e=>{const c=e.closest('.panel'),r=e.getBoundingClientRect(),p=c.getBoundingClientRect(),s=getComputedStyle(c);return r.left>=p.left+parseFloat(s.paddingLeft)-1&&r.right<=p.right-parseFloat(s.paddingRight)+1}));assert(controls);const last=p.locator('#generate-daily');await last.evaluate(e=>e.scrollIntoView({block:'end'}));const rr=await last.boundingBox(),nr=await p.locator('.bottom-nav').boundingBox();assert(rr.y+rr.height<=nr.y-8);await p.locator('#open-health').click();await p.locator('#health-paste').click();await p.locator('#health-json').fill(JSON.stringify(full));await scan();await p.locator('#parse-health').click();await scan();assert(await p.locator('#confirm-health').isEnabled());const scroll=await p.locator('#health-dialog .recovery-scroll').evaluate(e=>({overflow:getComputedStyle(e).overflowY,scroll:e.scrollHeight,client:e.clientHeight}));assert.equal(scroll.overflow,'auto');assert(scroll.scroll>scroll.client);await p.locator('#confirm-health').scrollIntoViewIfNeeded();const button=await p.locator('#confirm-health').boundingBox();assert(button.y+button.height<=height);if(width===390){await p.locator('#health-dialog .recovery-scroll').evaluate(e=>e.scrollTop=0);await p.screenshot({path:path.join(process.env.SCREENSHOT_DIR||'/tmp',name+'-health-preview.png')})}await p.locator('#edit-health').click();await p.setViewportSize({width,height:320});await p.locator('#health-json').focus();await scan();assert(await p.locator('#close-health').isVisible());await p.locator('#parse-health').click();await p.locator('#confirm-health').scrollIntoViewIfNeeded();assert(await p.locator('#confirm-health').isVisible());await p.locator('#close-health').click();await p.setViewportSize({width,height});for(const v of ['history','training']){await p.locator(`[data-view=${v}]`).click();await scan()}await p.locator('#open-import').click();await scan();await p.locator('#cancel-import').click();console.log(`${name} ${width}×${height}: sleep/card/sheet overflow=0, native fields contained, nav clear; 320px keyboard fixture scroll/close/parse/preview PASS`)}
assert.deepEqual(errors,[]);await p.goto(url+'/shortcuts-apple-health.html');await scan();assert.match(await p.locator('main').textContent(),/Find Health Samples/);await browser.close();console.log(name+': health schema/merge/summary/clipboard/date/reimport/removal/storage checks PASS')}
})().catch(e=>{console.error(e);process.exit(1)});
