const {chromium,webkit}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const KEY='haoxuan-training-log:v1',url=process.env.TEST_URL||'http://127.0.0.1:8765';
const example=kind=>fs.readFileSync(path.join(__dirname,`../examples/${kind}-plan.json`),'utf8');
const strength=JSON.parse(example('strength')),cardio=JSON.parse(example('cardio'));
function fixture(){
 const ex=(cn,i=0)=>({cn,ja:'テスト',en:'Test',weight:40,count:1,range:'8–12',done:true,sets:[{weight:42.5+i,reps:'10',rir:'0',feel:'normal',done:true}]});
 const b={date:'2026-09-05',type:'B',gym:'B历史健身房',exercises:[ex('高位下拉')],feedback:{overall:'很好',notes:'真实风格测试 B'},completed:true};
 const c={date:'2026-09-06',type:'C',gym:'C历史健身房',exercises:['腿举','坐姿腿弯举','腿屈伸','髋外展','髋内收','器械卷腹'].map(ex),feedback:{overall:'正常',stimulus:'正好',pain:'无'},completed:true};
 const d={date:'2026-09-07',type:'D',kind:'cardio',gym:'D历史健身房',exercises:[],feedback:{},completed:true,cardio:{selected:'treadmill',entries:{treadmill:{minutes:45,incline:11,speed:'5.0',rpe:'6',handrails:'否',feel:'normal',legFatigue:'2',pain:'无',notes:'',resistance:''}}}};
 return {version:1,templates:{A:[],B:[{...ex('B模板'),sets:undefined}],C:[],D:[]},records:{alternateB:b,'2026-09-06_C':{date:c.date,type:'C',gym:'空计划',exercises:[],feedback:{},completed:false},'2026-09-07_D':d},history:{oldC:c},sleep:{'2026-09-07':{bed:'01:00',asleep:'01:30',wakes:'1',wake:'10:00',hours:'8.5',nap:'20',caffeine:'13:00',rating0:'4',rating1:'3',rating2:'2',rating3:'3',rating4:'5',rating5:'2',notes:'旧睡眠'}},dailyStatusByDate:{'2026-09-07':{date:'2026-09-07',bedtime:'',estimatedSleepHours:null,afternoonFocus:5}},gym:'历史默认'};
}
(async()=>{for(const [name,engine] of [['chromium',chromium],['webkit',webkit]]){
 const browser=await engine.launch(),ctx=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:'block',...(name==='chromium'?{permissions:['clipboard-read','clipboard-write']}: {})}),p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(url);
 const raw=()=>p.evaluate(k=>localStorage.getItem(k),KEY),read=async()=>JSON.parse(await raw());
 assert.equal(await raw(),null,'visiting fresh environment must not create storage');await p.locator('[data-view=history]').click();assert((await p.locator('main').textContent()).includes('主屏幕 App'));await p.locator('#open-diagnostics').click();assert.equal((await p.evaluate(()=>diagnosticInfo())).exists,false);
 const original=JSON.parse(JSON.stringify(fixture()));await p.evaluate(({key,data})=>localStorage.setItem(key,JSON.stringify(data)),{key:KEY,data:original});await p.reload();const migrated=await raw();let data=await read();assert.deepEqual(data.records,original.records);assert.deepEqual(data.history,original.history);assert.deepEqual(data.sleep,original.sleep);const daily=data.dailyStatusByDate['2026-09-07'];assert.deepEqual(Object.fromEntries(Object.keys(daily).filter(k=>k!=='date').map(k=>[k,daily[k]])),{bedtime:'01:00',estimatedSleepHours:8.5,afternoonFocus:5,sleepTime:'01:30',nightAwakenings:1,wakeTime:'10:00',napMinutes:20,lastCaffeineTime:'13:00',wakeEnergy:4,morningFocus:3,muscleSoreness:3,trainingMotivation:5,daytimeSleepiness:2,notes:'旧睡眠'});await p.reload();assert.equal(await raw(),migrated,'migration idempotent');
 await p.locator('[data-view=history]').click();assert.equal(await p.locator('.history-item').count(),3);await p.locator('[data-history="2026-09-06_C"]').click();assert.equal(await p.locator('.exercise').count(),6);await p.locator('#generate').click();assert((await p.locator('#summary').inputValue()).includes('42.5×10 🟡 RIR0'));assert((await p.locator('#summary').inputValue()).includes('器械卷腹'));await p.locator('#close-summary').click();assert.equal(await raw(),migrated,'read selector does not persist normalized histories');
 await p.locator('#open-import').click();await p.locator('#plan-json').fill(JSON.stringify({...strength,date:'2026-09-06',type:'C'}));await p.locator('#parse-import').click();assert(await p.locator('#confirm-import').isDisabled(),'legacy actual blocks import despite empty shadow');await p.locator('#cancel-import').click();
 const alias=await p.evaluate(()=>{const r=normalizeLegacyWorkout({date:'2026-09-05',type:'B',exercises:[{nameZh:'兼容',nameJa:'テスト',nameEn:'Test',recommendedWeight:40,completed:true,sets:[{actualWeight:45,actualReps:11,RIR:0,feeling:'🟡普通',completed:true}]}]});return r});assert.equal(alias.exercises[0].sets[0].weight,45);assert.equal(alias.exercises[0].sets[0].rir,'0');assert.equal(alias.exercises[0].sets[0].feel,'normal');assert(alias.exercises[0].done);
 for(const kind of ['strength','cardio']){await p.locator('#open-import').click();const before=await raw();await p.locator(`[data-example=${kind}]`).click();await p.waitForFunction(k=>document.querySelector('#plan-json').value.includes(k),kind==='strength'?'exercises':'cardioOptions');assert.equal(await p.locator('#plan-json').inputValue(),example(kind));assert(await p.locator('#import-preview').isHidden());assert.equal(await raw(),before);await p.locator('#parse-import').click();assert(await p.locator('#import-preview').isVisible());assert.equal(await raw(),before);await p.locator('#cancel-import').click()}
 for(const text of [example('strength'),'\ufeff'+example('strength'),'```json\n'+example('strength')+'\n```','```anything\r\n'+example('strength')+'\r\n```']){await p.locator('#open-import').click();await p.locator('#plan-json').fill(text);await p.locator('#parse-import').click();assert(await p.locator('#import-preview').isVisible());await p.locator('#cancel-import').click()}
 for(const text of ['说明文字','{"schema":1,}',example('strength').trim().slice(0,-1),JSON.stringify({...strength,schema:'bad'}),JSON.stringify({...strength,version:9}),JSON.stringify({...strength,date:'2026-02-30'}),JSON.stringify({...strength,exercises:[{...strength.exercises[0],weight:-1}]}),example('strength').replace('"weight": 40','"weight": 1e309')]){const before=await raw();await p.locator('#open-import').click();await p.locator('#plan-json').fill(text);await p.locator('#parse-import').click();assert(await p.locator('#import-error').textContent());assert.equal(await raw(),before);await p.locator('#cancel-import').click()}
 await p.locator('[data-view=history]').click();await p.locator('#open-diagnostics').click();const info=await p.evaluate(()=>diagnosticInfo());assert.deepEqual(info.byType,{A:0,B:1,C:1,D:1});assert.equal(info.legacySleep,1);assert.equal(info.daily,1);assert.equal(info.shadows,1);assert.equal(info.workouts,3);assert(await p.locator('#raw-overview-content').isHidden());await p.locator('#raw-overview').click();assert(!(await p.locator('#raw-overview-content').textContent()).includes('真实风格测试 B'));
 const beforeExport=await raw();await p.locator('#export-backup').click();const backupText=await p.locator('#backup-output').inputValue(),backup=JSON.parse(backupText);assert.deepEqual(backup.data,await read());assert.equal(backup.environment,'browser');assert.equal(await raw(),beforeExport);if(name==='chromium'){await p.locator('#copy-backup').click();await p.waitForFunction(()=>document.querySelector('#backup-copy-status').textContent.includes('已复制'));assert.equal(await p.evaluate(()=>navigator.clipboard.readText()),backupText)}await p.locator('#close-export').click();
 // Both sides contain actual records: preview reports all conflicts and cannot write.
 await p.locator('#open-backup').click();await p.locator('#backup-input').fill(backupText);await p.locator('#parse-backup').click();assert(await p.locator('#confirm-backup').isDisabled());assert((await p.locator('#backup-preview-content').textContent()).includes('2026-09-06 C'));assert.equal(await raw(),beforeExport);await p.locator('#cancel-backup').click();
 // Isolated fresh context, never deletes a real user's key.
 const fresh=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:'block'}),q=await fresh.newPage();await q.goto(url);await q.locator('[data-view=history]').click();await q.locator('#open-diagnostics').click();await q.locator('#open-backup').click();await q.locator('#backup-input').fill(backupText);await q.locator('#parse-backup').click();assert.equal(await q.evaluate(k=>localStorage.getItem(k),KEY),null);await q.locator('#confirm-backup').click();const restored=await q.evaluate(()=>({records:getAllNormalizedWorkouts(),d:db.dailyStatusByDate,t:db.templates}));assert.equal(restored.records.length,3);assert(restored.records.every(r=>r.completed));assert.deepEqual(restored.d,backup.data.dailyStatusByDate);assert.deepEqual(restored.t,backup.data.templates);const restoredRaw=await q.evaluate(k=>localStorage.getItem(k),KEY);await q.reload();assert.equal(await q.evaluate(k=>localStorage.getItem(k),KEY),restoredRaw);await fresh.close();
 // Backup precedence: local actual stays byte-for-byte, imported actual beats empty.
 const merge=await p.evaluate(s=>{const actual=s.history.oldC;const empty={...actual,exercises:[],completed:false,feedback:{}};const local={version:1,records:{'2026-09-06_C':actual},dailyStatusByDate:{'2026-09-07':{afternoonFocus:5}}};const incoming={version:1,records:{'2026-09-06_C':empty},sleep:s.sleep};const out=mergeBackupData(local,incoming);return {same:JSON.stringify(out.next.records['2026-09-06_C'])===JSON.stringify(actual),d:out.next.dailyStatusByDate,reverse:mergeBackupData(incoming,local).next.records['2026-09-06_C'].completed}},original);assert(merge.same);assert(merge.reverse);assert.equal(merge.d['2026-09-07'].afternoonFocus,5);
 const blanks=await p.evaluate(s=>{const base={sleep:s.sleep,dailyStatusByDate:{'2026-09-07':{date:'2026-09-07'}}};const one=migrateDaily(base);return {day:one.dailyStatusByDate['2026-09-07'],stable:JSON.stringify(one)===JSON.stringify(migrateDaily(one))}},original);assert.equal(blanks.day.afternoonFocus,2);assert.equal(blanks.day.napMinutes,20);assert(blanks.stable);
 // Alternate container array and missing optional root fields stay readable.
 assert.equal(await p.evaluate(r=>getAllNormalizedWorkouts({records:[r]}).length,original.history.oldC),1);
 const scan=async()=>p.evaluate(()=>[...document.querySelectorAll('*')].filter(e=>{if(!e.getClientRects().length||e.closest('dialog:not([open])'))return false;const r=e.getBoundingClientRect();return r.width&&(r.left < -1||r.right>document.documentElement.clientWidth+1)}).map(e=>e.tagName+'.'+e.className));
 for(const [width,height]of [[320,568],[375,667],[390,844],[393,852],[430,932]]){
  await p.setViewportSize({width,height});
  for(const view of ['training','sleep','history']){await p.locator(`[data-view=${view}]`).click();await p.addStyleTag({content:'html,body{overflow-x:visible!important}'});assert.deepEqual(await scan(),[],`${name} ${width} ${view}`);if(view==='sleep'){assert.equal(await p.locator('.sleep-fields input').evaluateAll(list=>list.every(el=>{const r=el.getBoundingClientRect(),c=el.closest('.panel'),b=c.getBoundingClientRect(),s=getComputedStyle(c);return r.left>=b.left+parseFloat(s.paddingLeft)-1&&r.right<=b.right-parseFloat(s.paddingRight)+1&&Math.abs(r.height-52)<=1})),true)}const last=p.locator('main button').last();await last.evaluate(e=>e.scrollIntoView({block:'end'}));const r=await last.boundingBox(),nav=await p.locator('nav').boundingBox();assert(r.y+r.height<=nav.y-8)}
  await p.locator('[data-view=training]').click();await p.locator('#open-import').click();assert.deepEqual(await scan(),[]);const area=await p.locator('#plan-json').boundingBox();assert(area.width<=width-32);await p.locator('[data-example=strength]').click();await p.waitForFunction(()=>document.querySelector('#plan-json').value.includes('exercises'));await p.locator('#parse-import').click();assert.deepEqual(await scan(),[]);assert(await p.locator('#import-scroll').evaluate(e=>e.scrollHeight>e.clientHeight));await p.locator('#confirm-import').scrollIntoViewIfNeeded();const button=await p.locator('#confirm-import').boundingBox();assert(button.height>=48&&button.y+button.height<=height);if(width===390&&process.env.SCREENSHOT_DIR){await p.locator('#import-scroll').evaluate(e=>e.scrollTop=0);await p.screenshot({path:`${process.env.SCREENSHOT_DIR}/${name}-import-v021.png`})}await p.locator('#cancel-import').click();
  await p.locator('[data-view=history]').click();await p.locator('#open-diagnostics').click();assert.deepEqual(await scan(),[]);await p.locator('#open-backup').click();assert.deepEqual(await scan(),[]);await p.locator('#cancel-backup').click();console.log(`${name} ${width}×${height}: 0 overflow, status input bounds/52px, nav, import/recovery sheets PASS`);
 }
 await p.setViewportSize({width:390,height:320});await p.locator('[data-view=training]').click();await p.locator('#open-import').click();await p.locator('#plan-json').focus();await p.locator('#parse-import').scrollIntoViewIfNeeded();const close=await p.locator('#cancel-import').boundingBox();assert(close.y>=0&&close.y+close.height<320);await p.locator('#cancel-import').click();
 await p.setViewportSize({width:1280,height:900});for(const view of ['training','sleep','history']){await p.locator(`[data-view=${view}]`).click();assert.deepEqual(await scan(),[])}
 await p.evaluate(()=>Object.defineProperty(navigator,'standalone',{configurable:true,value:true}));await p.locator('[data-view=history]').click();await p.locator('#open-diagnostics').click();assert.equal((await p.evaluate(()=>diagnosticInfo())).environment,'Home Screen PWA');assert.equal((await p.evaluate(()=>exportBackup())).environment,'standalone');assert.deepEqual(errors,[]);assert.deepEqual((await read()).records,original.records);assert.deepEqual((await read()).history,original.history);
 // Broken/unknown storage must be visible and cannot silently write an empty workout.
 await p.evaluate(k=>localStorage.setItem(k,JSON.stringify({version:1,records:{mystery:{unknownPayload:[1,2]}}})),KEY);await p.reload();const unknown=await raw();assert((await p.locator('main').textContent()).includes('无法完全识别'));await p.locator('[data-view=history]').click();await p.locator('#open-diagnostics').click();assert((await p.evaluate(()=>diagnosticInfo())).unknown>0);assert.equal(await raw(),unknown);
 await p.evaluate(k=>localStorage.setItem(k,'{broken'),KEY);await p.reload();assert.equal(await raw(),'{broken');await p.locator('[data-view=history]').click();await p.locator('#open-diagnostics').click();await p.locator('#export-backup').click();assert.equal(await p.locator('#backup-output').inputValue(),'{broken');assert.equal(await raw(),'{broken');await browser.close();console.log(name+': legacy B/C/D, actual shadow selector, sleep field-fill/idempotence, examples/fences/errors, export/merge/conflicts, desktop/errors PASS');
}})().catch(e=>{console.error(e);process.exit(1)});
