const {chromium,webkit}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const baseline=require('./fixtures/v021-empty-geometry.json');
const KEY='haoxuan-training-log:v1',url=process.env.TEST_URL||'http://127.0.0.1:8765';
// Synthetic diagnostic counts only; these are not recovered user workouts.
function fixture(){const exercise={cn:'测试动作',ja:'テスト',en:'Test',weight:40,count:1,range:'8–12'};const record=(date,type)=>({date,type,gym:'测试健身房',exercises:[{...exercise,done:true,sets:[{weight:42.5,reps:'10',feel:'normal',rir:'2',done:true}]}],feedback:{overall:'正常'},completed:true});return {version:1,templates:{A:[],B:Array.from({length:5},()=>({...exercise})),C:Array.from({length:6},()=>({...exercise})),D:[]},records:{'2026-09-05_B':record('2026-09-05','B'),'2026-09-05_C':record('2026-09-05','C'),'2026-09-06_C':record('2026-09-06','C')},sleep:{'2026-09-05':{hours:'8'},'2026-09-06':{hours:'7'}},dailyStatusByDate:{'2026-09-05':{date:'2026-09-05',estimatedSleepHours:8},'2026-09-06':{date:'2026-09-06',estimatedSleepHours:7}},gym:'测试健身房'}}
(async()=>{for(const [name,engine]of [['chromium',chromium],['webkit',webkit]]){const b=await engine.launch(),ctx=await b.newContext({serviceWorkers:'block',viewport:{width:390,height:844}}),p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(url);const original=JSON.stringify(fixture());await p.evaluate(({key,raw})=>localStorage.setItem(key,raw),{key:KEY,raw:original});await p.reload();
const audit=async()=>p.evaluate(()=>{const overflow=[],layers=[],filters=[];for(const e of document.querySelectorAll('*')){if(!e.getClientRects().length)continue;const r=e.getBoundingClientRect(),s=getComputedStyle(e);if(r.width&&(r.left < -1||r.right>document.documentElement.clientWidth+1))overflow.push(e.tagName+'.'+e.className);if(['fixed','sticky'].includes(s.position)){const allowed=e.matches('.bottom-nav,#toast,dialog');layers.push({tag:e.tagName,id:e.id,top:r.top,bottom:r.bottom,allowed});}for(const pseudo of [null,'::before','::after',...(e.matches('dialog[open]')?['::backdrop']:[])]){const c=pseudo?getComputedStyle(e,pseudo):s;if(pseudo&&pseudo!=='::backdrop'&&['none','normal'].includes(c.content))continue;const blur=c.backdropFilter||c.webkitBackdropFilter||'none';if(c.filter!=='none'||blur!=='none')filters.push({tag:e.tagName,pseudo,filter:c.filter,backdrop:blur});}}return {overflow,layers,filters}});
const check=async()=>{const report=await audit();assert.deepEqual(report.overflow,[]);assert.deepEqual(report.filters,[],'no application-owned filter/backdrop-filter including pseudo layers');assert(report.layers.every(l=>l.allowed),'only nav, toast and open dialogs may be fixed');const nav=await p.locator('.bottom-nav').boundingBox();assert(Math.abs(nav.y+nav.height-(await p.evaluate(()=>innerHeight)))<=1);return report};
const results=[];
for(const [width,height]of [[320,568],[375,667],[390,844],[393,852],[430,932]]){await p.setViewportSize({width,height});await p.addStyleTag({content:'html,body{overflow-x:visible!important}'});await p.locator('[data-view=training]').click();await p.locator('[data-choice=type][data-value=A]').click();const alignment=await p.locator('.empty').evaluate(e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e),center=x=>x.left+x.width/2;return {width:r.width,height:r.height,padding:s.padding,borderRadius:s.borderRadius,deltas:[...e.children].map(x=>center(x.getBoundingClientRect())-center(r)),text:[...e.children].map(x=>getComputedStyle(x).textAlign)}});for(const k of ['width','height'])assert(Math.abs(alignment[k]-baseline[name][width][k])<=1,`${name}/${width} card ${k} unchanged`);assert.equal(alignment.padding,baseline[name][width].padding);assert.equal(alignment.borderRadius,baseline[name][width].borderRadius);assert(alignment.deltas.every(d=>Math.abs(d)<=2));assert(alignment.text.every(t=>t==='center'));if(width===390&&process.env.SCREENSHOT_DIR){await p.locator('.empty').evaluate(e=>e.scrollIntoView({block:'center'}));await p.screenshot({path:path.join(process.env.SCREENSHOT_DIR,name+'-v022-empty.png')})}
for(const view of ['training','sleep','history']){await p.locator(`[data-view=${view}]`).click();await check();await p.evaluate(()=>scrollTo(0,150));await check();const last=p.locator('main button').last();await last.evaluate(e=>e.scrollIntoView({block:'end'}));const r=await last.boundingBox(),nav=await p.locator('.bottom-nav').boundingBox();assert(r.y+r.height<=nav.y-8)}
await p.locator('#open-diagnostics').click();await check();await p.evaluate(()=>scrollTo(0,60));await check();if(width===390&&process.env.SCREENSHOT_DIR){await p.evaluate(()=>scrollTo(0,0));await p.screenshot({path:path.join(process.env.SCREENSHOT_DIR,name+'-v022-diagnostics.png')})}
await p.locator('[data-view=training]').click();await p.locator('#open-import').click();await check();await p.locator('[data-example=strength]').click();await p.waitForFunction(()=>document.querySelector('#plan-json').value.includes('exercises'));await p.locator('#parse-import').click();await check();await p.locator('#confirm-import').scrollIntoViewIfNeeded();await p.locator('#cancel-import').click();results.push({width,height,overflow:0,topBlurLayers:0,titleDelta:alignment.deltas[0],descriptionDelta:alignment.deltas[1]});}
// One diagnostic fixture regression per engine, entire original storage byte-identical.
const d=await p.evaluate(()=>diagnosticInfo());assert.equal(d.strength,3);assert.equal(d.cardio,0);assert.deepEqual(d.byType,{A:0,B:1,C:2,D:0});assert.equal(d.daily,2);assert.equal(d.legacySleep,2);assert.equal(d.earliest,'2026-09-05');assert.equal(d.latest,'2026-09-06');assert.equal(await p.evaluate(k=>localStorage.getItem(k),KEY),original);
// Explicit geometry simulation: env() is zero in desktop engines. Do not call
// this a real iPhone safe-area or installation test.
await p.setViewportSize({width:390,height:844});
// Substitute env values before app startup so its existing nav measurement
// observes the safe-area geometry, as it does on the initial PWA load.
await p.route('**/styles.css',route=>route.fulfill({contentType:'text/css',body:fs.readFileSync(path.join(__dirname,'../styles.css'),'utf8').replaceAll('env(safe-area-inset-top,0px)','59px').replaceAll('env(safe-area-inset-bottom)','34px')}));
await p.reload();await p.addStyleTag({content:'html,body{overflow-x:visible!important}'});await p.evaluate(()=>scrollTo(0,0));const shifted=await p.locator('.brand').boundingBox();assert.equal(shifted.y,59);assert.equal(await p.locator('body').evaluate(e=>getComputedStyle(e).position),'static');await check();const last=p.locator('main button').last();await last.evaluate(e=>e.scrollIntoView({block:'end'}));const r=await last.boundingBox(),nav=await p.locator('.bottom-nav').boundingBox();assert(r.y+r.height<=nav.y-8);await p.unroute('**/styles.css');await p.reload();
await p.setViewportSize({width:390,height:320});await p.locator('#open-import').click();await p.locator('#plan-json').focus();await p.locator('#parse-import').scrollIntoViewIfNeeded();const close=await p.locator('#cancel-import').boundingBox();assert(close.y>=0&&close.y+close.height<320);await check();await p.locator('#cancel-import').click();
await p.setViewportSize({width:1280,height:844});await p.locator('[data-choice=type][data-value=A]').click();const desktop=await p.locator('.empty').boundingBox();assert(Math.abs(desktop.height-baseline[name][1280].height)<=1);await check();assert.deepEqual(errors,[]);console.log(name,JSON.stringify(results));console.log(name+': unchanged card geometry, safe-area simulation, modal, diagnostic 3 Strength/0 Cardio/2 Daily Status and unchanged storage PASS');await b.close()}
// Guard exact production scope by content hashes, not mocked data behavior.
const crypto=require('node:crypto'),hashes=require('./fixtures/v021-data-hashes.json');for(const [file,hash]of Object.entries(hashes))assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(__dirname,'..',file))).digest('hex'),hash,file+' data implementation must remain byte-identical');console.log('Data code, manifest and examples byte-identical to v0.2.1 PASS');})().catch(e=>{console.error(e);process.exit(1)});
