const {chromium,webkit}=require('playwright');const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const baseline=require('./fixtures/v021-empty-geometry.json'),hashes=require('./fixtures/v021-data-hashes.json');const url=process.env.TEST_URL||'http://127.0.0.1:8765',KEY='haoxuan-training-log:v1';
function fixture(){const e={cn:'测试',ja:'テスト',en:'Test',weight:40,count:1,range:'8–12',done:true,sets:[{weight:42,reps:10,rir:2,feel:'normal',done:true}]},r=(date,type)=>({date,type,gym:'测试健身房',exercises:[e],feedback:{},completed:true});return {version:1,records:{'2026-09-05_B':r('2026-09-05','B'),'2026-09-05_C':r('2026-09-05','C'),'2026-09-06_C':r('2026-09-06','C')},templates:{A:[],B:[],C:[],D:[]},sleep:{'2026-09-05':{hours:8},'2026-09-06':{hours:7}},dailyStatusByDate:{'2026-09-05':{date:'2026-09-05',estimatedSleepHours:8},'2026-09-06':{date:'2026-09-06',estimatedSleepHours:7}}}}
(async()=>{for(const [name,engine]of [['chromium',chromium],['webkit',webkit]]){const b=await engine.launch();for(const mode of ['browser','standalone']){const ctx=await b.newContext({viewport:{width:390,height:844},serviceWorkers:'block'}),page=await ctx.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await ctx.addInitScript(({mode,key,data})=>{const nativeMatch=window.matchMedia.bind(window);window.matchMedia=query=>{const m=nativeMatch(query);if(query==='(display-mode: standalone)')Object.defineProperty(m,'matches',{value:mode==='standalone'});return m};Object.defineProperty(navigator,'standalone',{value:mode==='standalone'});if(location.pathname!=='/ui-status-fixture')localStorage.setItem(key,JSON.stringify(data))},{mode,key:KEY,data:fixture()});
if(mode==='standalone'){
 // Synthetic host chrome: 59px top status area and 34px home-indicator area.
 // The actual app frame receives an already-inset viewport. This does not
 // emulate iOS compositing, installation metadata, or its native status bar.
 await page.route('**/ui-status-fixture',r=>r.fulfill({contentType:'text/html',body:'<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><style>html,body{margin:0;background:#eee}iframe{display:block;border:0;width:100%;height:calc(100dvh - 93px)}</style><div style="height:59px">Simulated system status area</div><iframe src="./" title="app"></iframe><div style="height:34px">Simulated Home Indicator</div>'}));await page.goto(url+'/ui-status-fixture');await page.frameLocator('iframe').locator('#app h1').waitFor();
}else await page.goto(url);
const p=mode==='standalone'?page.frames().find(f=>f.parentFrame()):page;const raw=()=>p.evaluate(k=>localStorage.getItem(k),KEY),original=await raw();
const check=async()=>{const a=await p.evaluate(()=>{const bad=[],layers=[];for(const e of document.querySelectorAll('*')){if(!e.getClientRects().length)continue;const r=e.getBoundingClientRect(),s=getComputedStyle(e);if(r.width&&(r.left < -1||r.right>document.documentElement.clientWidth+1))bad.push(e.tagName+'.'+e.className);const backdrop=s.backdropFilter||s.webkitBackdropFilter||'none';if(backdrop!=='none'||s.filter!=='none')layers.push(e.tagName);if(['fixed','sticky'].includes(s.position)&&!e.matches('.bottom-nav,#toast,dialog'))layers.push(e.tagName)}const nav=document.querySelector('.bottom-nav').getBoundingClientRect();return {bad,layers,bodyPadding:getComputedStyle(document.body).paddingTop,navBottom:nav.bottom,height:innerHeight}});assert.deepEqual(a.bad,[]);assert.deepEqual(a.layers,[]);assert.equal(a.bodyPadding,'0px');assert(Math.abs(a.navBottom-a.height)<=1)};
for(const [width,height]of [[320,568],[375,667],[390,844],[393,852],[430,932]]){await page.setViewportSize({width,height});await p.addStyleTag({content:'html,body{overflow-x:visible!important}'});await p.locator('[data-view=training]').click();await p.locator('[data-choice=type][data-value=A]').click();await p.evaluate(()=>scrollTo(0,0));await check();const head=await p.locator('.brand').boundingBox();assert.equal(head.y,mode==='standalone'?59:0,'header starts after host status region, no duplicate inset');
const group=await p.locator('.empty').evaluate(e=>{const c=e.getBoundingClientRect(),g=e.querySelector('.empty-state-content').getBoundingClientRect(),x=r=>r.left+r.width/2,y=r=>r.top+r.height/2;return {width:c.width,height:c.height,dy:y(g)-y(c),dx:[...e.querySelectorAll('h3,p')].map(t=>x(t.getBoundingClientRect())-x(c)),padding:getComputedStyle(e).padding}});assert(Math.abs(group.dy)<=4);assert(group.dx.every(x=>Math.abs(x)<=2));assert(Math.abs(group.height-baseline[name][width].height)<=1);assert.equal(group.width,baseline[name][width].width);assert.equal(group.padding,baseline[name][width].padding);
if(width===390&&process.env.SCREENSHOT_DIR){await p.locator('.empty').evaluate(e=>e.scrollIntoView({block:'center'}));await page.screenshot({path:path.join(process.env.SCREENSHOT_DIR,`${name}-${mode}-v023-empty.png`)})}
for(const view of ['sleep','history']){await p.locator(`[data-view=${view}]`).click();await check()}await p.locator('#open-diagnostics').click();await check();const info=await p.evaluate(()=>pwaViewportInfo());assert.equal(info.displayMode,mode);assert.equal(info.navigatorStandalone,mode==='standalone');assert.equal(info.viewport,'width=device-width,initial-scale=1');assert.equal(info.statusBarStyle,'default');assert.equal(info.themeColor,'#142c28');assert.equal(await p.locator('#pwa-ui-values dt').count(),11);await p.locator('#pwa-ui-diagnostics').evaluate(e=>e.scrollIntoView({block:'end'}));if(width===390&&process.env.SCREENSHOT_DIR)await page.screenshot({path:path.join(process.env.SCREENSHOT_DIR,`${name}-${mode}-v023-diagnostics.png`)});
await p.locator('[data-view=training]').click();await p.locator('#open-import').click();await check();await p.locator('#cancel-import').click();const last=p.locator('main button').last();await last.evaluate(e=>e.scrollIntoView({block:'end'}));const r=await last.boundingBox(),nav=await p.locator('.bottom-nav').boundingBox();assert(r.y+r.height<=nav.y-8);assert.equal(await raw(),original);console.log(`${name} ${mode} ${width}×${height}: overflow=0, top layers=0, group dy=${group.dy}, dx=${group.dx.join('/')}, card height unchanged`)}
await p.locator('[data-view=history]').click();await p.locator('#open-diagnostics').click();const stats=await p.evaluate(()=>diagnosticInfo());assert.equal(stats.strength,3);assert.deepEqual(stats.byType,{A:0,B:1,C:2,D:0});assert.equal(stats.daily,2);const before=await p.evaluate(()=>pwaViewportInfo().innerHeight);await page.setViewportSize({width:390,height:500});await p.waitForFunction(old=>pwaViewportInfo().innerHeight!==old,before);await p.waitForFunction(()=>{const terms=[...document.querySelectorAll('#pwa-ui-values dt')];return terms.find(e=>e.textContent==='window.innerHeight').nextElementSibling.textContent===innerHeight+' px'});
// A nonzero reported env inset is diagnostic information, not body padding.
const envStyle=await p.addStyleTag({content:'[data-pwa-safe-area-probe]{padding-top:59px!important}'});assert.equal(await p.evaluate(()=>pwaViewportInfo().safeAreaTop),59);assert.equal(await p.locator('body').evaluate(e=>getComputedStyle(e).paddingTop),'0px');await envStyle.evaluate(e=>e.remove());assert.equal(await raw(),original);assert.deepEqual(errors,[]);await ctx.close()}
await b.close()}
for(const [file,hash]of Object.entries(hashes)){let text=fs.readFileSync(path.join(__dirname,'..',file),'utf8');if(file==='app.js')text=text.replace('<div class="panel empty"><div class="empty-state-content"><h3>今天还没有训练计划</h3><p class="muted">从 ChatGPT 获取今日训练计划后即可导入。</p></div></div>','<div class="panel empty"><h3>今天还没有训练计划</h3><p class="muted">从 ChatGPT 获取今日训练计划后即可导入。</p></div>');if(file==='data-recovery.js')text=text.replace('${pwaDiagnosticsPanel()}','');assert.equal(crypto.createHash('sha256').update(text).digest('hex'),hash,'Only the allowed UI template additions may differ: '+file)}console.log('Data implementation unchanged after removing the two UI-only markup additions PASS');})().catch(e=>{console.error(e);process.exit(1)});
