// Requires Playwright; TEST_URL defaults to the local test server. Uses isolated data only.
const {chromium,webkit}=require('playwright');const assert=require('node:assert/strict');
const KEY='haoxuan-training-log:v1',MARK='haoxuan-training-log:plan:2026-09-06-C';
const ex={cn:'旧C动作',ja:'テスト',en:'Test',weight:20,count:1,range:'8–12'};
const rec=(date,type)=>({date,type,gym:'Anytime成增',exercises:[{...ex,done:false,sets:[{weight:20,reps:'',feel:'',rir:'',done:false}]}],feedback:{},completed:false});
const base=()=>({version:1,templates:{A:[],B:[{...ex,cn:'B模板必须保留'}],C:[ex],D:[]},records:{'2026-09-05_B':{...rec('2026-09-05','B'),completed:true,feedback:{overall:'很好',stimulus:'正好',pain:'无'}},'2026-08-31_C':rec('2026-08-31','C')},sleep:{'2026-09-05':{bed:'23:30',hours:'7.5',notes:'保留睡眠'}},gym:'Anytime成增'});
(async()=>{for(const [name,engine]of [['chromium',chromium],['webkit',webkit]]){const b=await engine.launch();
const cases=['absent','empty','pristine-preset','weight','reps','rir-zero','feel','set-done','exercise-done','completed','notes','updated'];
for(const scenario of cases){const ctx=await b.newContext({serviceWorkers:'block'}),p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));const data=base();if(scenario!=='absent'){const r=rec('2026-09-06','C');data.records['2026-09-06_C']=r;if(scenario==='empty')r.exercises=[];if(scenario==='weight')r.exercises[0].sets[0].weight=25;if(scenario==='reps')r.exercises[0].sets[0].reps='8';if(scenario==='rir-zero')r.exercises[0].sets[0].rir='0';if(scenario==='feel')r.exercises[0].sets[0].feel='hard';if(scenario==='set-done')r.exercises[0].sets[0].done=true;if(scenario==='exercise-done')r.exercises[0].done=true;if(scenario==='completed')r.completed=true;if(scenario==='notes')r.feedback.notes='我的备注';if(scenario==='updated')r.updated=1}
await ctx.addInitScript(({key,data})=>{if(!localStorage.getItem(key))localStorage.setItem(key,JSON.stringify(data))},{key:KEY,data});await p.goto(process.env.TEST_URL||'http://127.0.0.1:8765');let saved=await p.evaluate(k=>JSON.parse(localStorage.getItem(k)),KEY);
assert.deepEqual(saved.records['2026-09-05_B'],data.records['2026-09-05_B']);assert.deepEqual(saved.records['2026-08-31_C'],data.records['2026-08-31_C']);assert.deepEqual(saved.sleep,data.sleep);assert.deepEqual(saved.templates.B,data.templates.B);assert.equal(saved.gym,data.gym);assert.equal(saved.version,1);assert.equal(saved.templates.C.length,6);
const conflict=!['absent','empty','pristine-preset'].includes(scenario);if(conflict){assert.deepEqual(saved.records['2026-09-06_C'],data.records['2026-09-06_C']);assert.equal(await p.evaluate(k=>localStorage.getItem(k),MARK),'conflict-preserved');assert((await p.locator('#toast').textContent()).includes('已保留原记录'))}else{const r=saved.records['2026-09-06_C'];assert.equal(r.gym,'Anytime成増');assert.equal(r.exercises.length,6);assert.equal(r.exercises.reduce((n,e)=>n+e.sets.length,0),15);assert.deepEqual(r.exercises.map(e=>e.weight),[42.5,45,60,55,32.5,37.5]);assert(r.feedback.notes.includes('机器显示重量'));assert(r.feedback.notes.includes('60–90秒'));
await p.locator('[data-field=date]').fill('2026-09-06');await p.locator('[data-choice=type][data-value=C]').click();assert.equal(await p.locator('.exercise').count(),6);assert.equal(await p.locator('#progress').getAttribute('max'),'15');await p.locator('[data-field="exercises.0.sets.0.weight"]').fill('40');saved=await p.evaluate(k=>JSON.parse(localStorage.getItem(k)),KEY);assert.equal(saved.records['2026-09-06_C'].exercises[0].sets[0].weight,'40');assert.equal(saved.records['2026-09-06_C'].exercises[0].sets[1].weight,42.5);await p.locator('#generate').click();const text=await p.locator('#summary').inputValue();assert(text.startsWith('【9/6 C日｜Anytime成増】'));assert(text.includes('腿屈伸\n60×'));await p.locator('#close-summary').click();
// Later C dates use the new template; previous C history stays intact.
await p.locator('[data-field=date]').fill('2026-09-10');assert.equal(await p.locator('.exercise').count(),6);}
const beforeReload=await p.evaluate(k=>localStorage.getItem(k),KEY);await p.reload();assert.equal(await p.evaluate(k=>localStorage.getItem(k),KEY),beforeReload);
// The one-time migration must not undo subsequent template edits.
await p.evaluate(k=>{const d=JSON.parse(localStorage.getItem(k));d.templates.C[0].weight=41;localStorage.setItem(k,JSON.stringify(d))},KEY);await p.reload();assert.equal(await p.evaluate(k=>JSON.parse(localStorage.getItem(k)).templates.C[0].weight,KEY),41);assert.deepEqual(errors,[]);await ctx.close()}
await b.close();console.log(`${name}: 12 migration/conflict scenarios, 15 sets, individual weight editing, old B/C/sleep preserved, future template, summary and idempotence PASS`)}})().catch(e=>{console.error(e);process.exit(1)});
