const {chromium,webkit}=require('playwright');const assert=require('node:assert/strict');
const KEY='haoxuan-training-log:v1';
const oldRec=(date,type)=>({date,type,gym:'旧健身房',completed:true,exercises:[{cn:'旧动作',ja:'テスト',en:'Test',weight:20,count:1,range:'8–12',done:true,sets:[{weight:20,reps:'10',feel:'normal',rir:'1',done:true}]}],feedback:{overall:'正常',stimulus:'正好',pain:'无'}});
const seed=()=>({version:1,templates:{A:[],B:[],C:[],D:[]},records:{'2026-09-05_B':oldRec('2026-09-05','B'),'2026-09-06_C':oldRec('2026-09-06','C')},sleep:{'2026-09-06':{hours:7}},gym:'旧健身房'});
(async()=>{for(const [name,engine]of [['chromium',chromium],['webkit',webkit]]){const browser=await engine.launch();for(const scenario of ['missing','empty','legacy-data','weight-only']){const ctx=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:'block'}),page=await ctx.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));const db=seed();if(scenario!=='missing')db.records['2026-09-07_D']=scenario==='empty'?{date:'2026-09-07',type:'D',gym:db.gym,completed:false,exercises:[],feedback:{}}:oldRec('2026-09-07','D');if(scenario==='weight-only'){const r=db.records['2026-09-07_D'];r.completed=false;r.exercises[0].done=false;Object.assign(r.exercises[0].sets[0],{done:false,weight:25,reps:'',feel:'',rir:''})}
await ctx.addInitScript(({db,key})=>{if(!localStorage.getItem(key)){localStorage.setItem(key,JSON.stringify(db));localStorage.setItem('haoxuan-training-log:plan:2026-09-06-C','applied')}},{db,key:KEY});await page.goto(process.env.TEST_URL||'http://127.0.0.1:8765');const read=()=>page.evaluate(k=>JSON.parse(localStorage.getItem(k)),KEY);let saved=await read();for(const key of ['2026-09-05_B','2026-09-06_C'])assert.deepEqual(saved.records[key],db.records[key]);assert.deepEqual(saved.templates,db.templates);assert.deepEqual(saved.sleep,db.sleep);
if(scenario.includes('data')||scenario==='weight-only'){assert.deepEqual(saved.records['2026-09-07_D'],db.records['2026-09-07_D']);assert((await page.locator('#toast').textContent()).includes('保留原记录'));await ctx.close();continue}
await page.locator('[data-field=date]').fill('2026-09-07');await page.locator('[data-choice=type][data-value=D]').click();assert.equal(await page.locator('[data-field=gym]').inputValue(),'Anytime豊玉桜台');assert.equal(await page.locator('[data-field$=".minutes"]').inputValue(),'45');assert(!/RIR|重量 kg|目标组数/.test(await page.locator('main').textContent()));
for(const [width,height]of [[320,568],[375,667],[390,844],[393,852],[430,932]]){await page.setViewportSize({width,height});await page.addStyleTag({content:'html,body{overflow-x:visible!important}'});const bad=await page.evaluate(()=>[...document.querySelectorAll('*')].filter(e=>{if(!e.getClientRects().length)return false;const r=e.getBoundingClientRect();return r.width&&(r.left < -1||r.right>innerWidth+1)}).map(e=>e.outerHTML));assert.deepEqual(bad,[]);await page.locator('#generate').evaluate(e=>e.scrollIntoView({block:'end'}));const target=await page.locator('#generate').boundingBox(),nav=await page.locator('nav').boundingBox();assert(target.y+target.height<=nav.y-8)}
for(const plan of ['treadmill','elliptical','bike']){if(plan!=='treadmill'){await page.locator('#cardio-alternatives').click();await page.locator(`[data-cplan=${plan}]`).click();assert(!(await read()).records['2026-09-07_D'].completed);assert.equal(await page.locator('[data-field$=".incline"]').count(),0);await page.locator('[data-field$=".resistance"]').fill(plan==='bike'?'轻到中等':'中等')}
for(const [key,value]of [['rpe','6'],['handrails','否'],['feel','normal'],['legFatigue','2'],['pain','无']])await page.locator(`[data-choice$=".${key}"][data-value="${value}"]`).click();await page.locator('#finish-cardio').click();assert((await read()).records['2026-09-07_D'].completed);await page.locator('#generate').click();const text=await page.locator('#summary').inputValue();assert(text.startsWith('【9/7 D日｜Anytime豊玉桜台】'));assert(!/kg|RIR|组数|×/.test(text));assert(text.includes('状态：已完成'));if(plan==='treadmill')assert(text.includes('45min｜11%｜5.0km/h\nRPE6｜扶手：否'));else assert(text.includes('阻力：'));await page.locator('#close-summary').click()}
await page.locator('#cardio-alternatives').click();await page.locator('[data-cplan=treadmill]').click();assert.equal(await page.locator('[data-choice$=".rpe"][aria-pressed=true]').textContent(),'6');await page.locator('[data-cstep=minutes][data-delta="5"]').click();assert.equal(await page.locator('[data-field$=".minutes"]').inputValue(),'50');await page.locator('#finish-cardio').click();const persisted=await read();await page.reload();assert.deepEqual(await read(),persisted);await page.locator('[data-view=history]').click();assert((await page.locator('[data-history="2026-09-07_D"]').textContent()).includes('已完成'));await page.locator('[data-history="2026-09-05_B"]').click();await page.locator('#generate').click();const strength=await page.locator('#summary').inputValue();assert(strength.includes('20×10 🟡 RIR1'));assert(!strength.includes('RPE'));assert.deepEqual(errors,[]);await ctx.close()}
await browser.close();console.log(name+': dated injection/conflicts, A/B/C preservation, three cardio plans, isolated drafts, completion/summary/persistence, five mobile widths and nav clearance PASS')}})().catch(e=>{console.error(e);process.exit(1)});
